import os
import shutil
from typing import List
from models import Recipe, RecipeAsset


def prepare_workspace(recipe_id: int, recipe: Recipe = None) -> str:
    """
    Creates isolated workspace directory structure for mkosi build.
    """
    base_dir = os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace")
    recipe_ws = os.path.join(base_dir, str(recipe_id))

    subdirs = [
        "output",
        "assets",
        "gpg_keys",
        "mkosi.extra/etc/apt/sources.list.d",
        "mkosi.extra/etc/apt/trusted.gpg.d",
        "mkosi.extra/root/.ssh",
        "mkosi.extra/etc/network/interfaces.d",
        "mkosi.extra/opt/custom"
    ]

    # Clean stale hook scripts from previous runs
    for old_hook in ["mkosi.postinst", "mkosi.postinst.chroot", "mkosi.finalize", "mkosi.finalize.chroot", "mkosi.prepare", "mkosi.prepare.chroot"]:
        old_h_path = os.path.join(recipe_ws, old_hook)
        if os.path.exists(old_h_path):
            try:
                os.remove(old_h_path)
            except Exception:
                pass

    for d in subdirs:
        os.makedirs(os.path.join(recipe_ws, d), exist_ok=True)

    repart_dir = os.path.join(recipe_ws, "mkosi.repart")
    if os.path.exists(repart_dir):
        shutil.rmtree(repart_dir, ignore_errors=True)
    os.makedirs(repart_dir, exist_ok=True)

    partitions = (recipe.partitions if (recipe and recipe.partitions) else None) or [
        {"mountpoint": "/boot", "size": "512M", "filesystem": "vfat", "type": "esp", "label": "edgeboot"},
        {"mountpoint": "/", "size": "8G", "filesystem": "ext4", "type": "root", "label": "edgeroot"},
        {"mountpoint": "/var/log/edge", "size": "1G", "filesystem": "ext4", "type": "generic", "label": "edgelog"},
        {"mountpoint": "/var/opt/edge", "size": "max", "filesystem": "ext4", "type": "generic", "label": "edgestor"},
    ]

    for idx, p in enumerate(partitions, start=1):
        p_type = (p.get("type") or "generic").lower()
        p_fs = (p.get("filesystem") or "ext4").lower()
        p_size = str(p.get("size") or "2G")
        p_mount = p.get("mountpoint") or "/"
        p_label = p.get("label") or f"part{idx}"

        conf_filename = f"{idx * 10:02d}-{p_type}-{p_label}.conf"
        conf_path = os.path.join(repart_dir, conf_filename)

        lines = ["[Partition]"]
        if p_type == "esp":
            lines.append("Type=esp")
            lines.append("Format=vfat")
            lines.append("CopyFiles=/boot:/")
        elif p_type == "root":
            lines.append("Type=root")
            lines.append(f"Format={p_fs}")
            lines.append("CopyFiles=/")
        elif p_type == "swap":
            lines.append("Type=swap")
            lines.append("Format=swap")
        else:
            lines.append("Type=linux-generic")
            lines.append(f"Format={p_fs}")
            if p_mount and p_mount != "/":
                lines.append(f"CopyFiles={p_mount}")

        if p_label:
            lines.append(f"Label={p_label}")

        if p_size and p_size.lower() not in ["max", "100%", "auto"]:
            size_val = p_size.upper()
            if not size_val.endswith("M") and not size_val.endswith("G") and not size_val.endswith("B"):
                size_val += "M"
            lines.append(f"SizeMinBytes={size_val}")

        with open(conf_path, "w") as f:
            f.write("\n".join(lines) + "\n")

    rel = (recipe.release if recipe else "bookworm") or "bookworm"
    cache_base = os.path.join(base_dir, "cache")
    os.makedirs(os.path.join(cache_base, "apt", "partial"), exist_ok=True)
    os.makedirs(os.path.join(cache_base, f"apt_{rel}", "partial"), exist_ok=True)
    if os.path.exists(cache_base):
        for item in os.listdir(cache_base):
            if item.startswith("apt"):
                os.makedirs(os.path.join(cache_base, item, "partial"), exist_ok=True)

    return recipe_ws


def populate_extra_tree(recipe: Recipe, assets: List[RecipeAsset], workspace_path: str):
    """
    Populates mkosi.extra/ overlay tree with SSH keys, custom APT repositories, assets, postinst, firstboot, and preseed files.
    """
    extra_dir = os.path.join(workspace_path, "mkosi.extra")

    # 1. SSH Keys
    if recipe.ssh_keys:
        ssh_dir = os.path.join(extra_dir, "root", ".ssh")
        os.makedirs(ssh_dir, exist_ok=True)
        auth_keys_path = os.path.join(ssh_dir, "authorized_keys")
        with open(auth_keys_path, "w") as f:
            f.write("\n".join(recipe.ssh_keys) + "\n")

    # 1.5. Static Hostname Overlay and /etc/fstab
    etc_dir = os.path.join(extra_dir, "etc")
    os.makedirs(etc_dir, exist_ok=True)
    if recipe.hostname:
        with open(os.path.join(etc_dir, "hostname"), "w") as f:
            f.write(recipe.hostname.strip().lower() + "\n")

    fstab_lines = [
        "# /etc/fstab: generated by D.U.R.O. image builder",
        "LABEL=edgeroot    /               ext4    defaults,rw          0    1",
        "LABEL=edgelog     /var/log/edge   ext4    defaults,nofail      0    2",
        "LABEL=edgestor    /var/opt/edge   ext4    defaults,nofail      0    2",
    ]
    with open(os.path.join(etc_dir, "fstab"), "w") as f:
        f.write("\n".join(fstab_lines) + "\n")

    # 2. Custom APT Repositories (Populated into both mkosi.skeleton and mkosi.extra)
    rel = recipe.release or "bookworm"
    repo_lines = []
    if recipe.repositories and isinstance(recipe.repositories, list):
        for repo in recipe.repositories:
            if isinstance(repo, dict) and repo.get("url"):
                url = repo.get("url")
                suite = repo.get("suite") or rel
                comp = repo.get("components") or "main"
                repo_lines.append(f"deb [trusted=yes] {url} {suite} {comp}")

    if repo_lines:
        for base_tree in ["mkosi.skeleton", "mkosi.extra"]:
            sources_dir = os.path.join(workspace_path, base_tree, "etc", "apt", "sources.list.d")
            os.makedirs(sources_dir, exist_ok=True)
            with open(os.path.join(sources_dir, "custom.list"), "w") as f:
                f.write("\n".join(repo_lines) + "\n")

    # 3. Assets overlay
    for asset in assets:
        if os.path.exists(asset.file_path):
            if asset.install_target:
                target_rel = asset.install_target.lstrip("/")
                dest_file = os.path.join(extra_dir, target_rel)
            else:
                dest_file = os.path.join(extra_dir, "opt", "custom", asset.filename)

            os.makedirs(os.path.dirname(dest_file), exist_ok=True)
            shutil.copy2(asset.file_path, dest_file)

    # 3.4. Release-Isolated Persistent APT Package Cache configuration
    rel_clean = (recipe.release if recipe and recipe.release else "default").lower().replace(" ", "_")
    release_apt_cache = os.path.join(os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace"), "cache", f"apt_{rel_clean}")
    os.makedirs(release_apt_cache, exist_ok=True)

    # Pre-seed rootfs APT cache directory from persistent host cache
    extra_apt_archives = os.path.join(workspace_path, "mkosi.extra", "var", "cache", "apt", "archives")
    os.makedirs(extra_apt_archives, exist_ok=True)
    if os.path.exists(release_apt_cache):
        for cached_file in os.listdir(release_apt_cache):
            if cached_file.endswith(".deb"):
                src_p = os.path.join(release_apt_cache, cached_file)
                dst_p = os.path.join(extra_apt_archives, cached_file)
                if not os.path.exists(dst_p):
                    try:
                        shutil.copy2(src_p, dst_p)
                    except Exception:
                        pass

    # 3.5. Prepare script — runs on HOST before package installation (mkosi v14)
    # Uses $BUILDROOT to access the rootfs. Writes custom repos and runs apt-get update
    # so that edge packages are resolvable when mkosi runs apt-get install.
    prepare_script_lines = [
        "#!/bin/bash",
        "set -e",
        'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH',
        '',
        '# Determine rootfs path — mkosi v14 passes $BUILDROOT',
        'ROOT="${BUILDROOT:-/}"',
        '',
        '# Write custom APT repos into the rootfs',
        'mkdir -p "$ROOT/etc/apt/sources.list.d"',
        "cat << 'REPOEOF' > \"$ROOT/etc/apt/sources.list.d/custom.list\"",
    ]
    prepare_script_lines.extend(repo_lines)
    prepare_script_lines.extend([
        "REPOEOF",
        '',
        '# Run apt-get update inside the rootfs chroot',
        '# Ensure host DNS resolv.conf is copied into rootfs so APT can resolve hosts',
        'cp -f /etc/resolv.conf "$ROOT/etc/resolv.conf" 2>/dev/null || true',
        'if [ "$ROOT" != "/" ] && [ -d "$ROOT/usr" ]; then',
        '  chroot "$ROOT" apt-get update --allow-insecure-repositories || true',
        'elif command -v apt-get >/dev/null 2>&1; then',
        '  apt-get update --allow-insecure-repositories || true',
        'fi',
    ])

    prepare_path = os.path.join(workspace_path, "mkosi.prepare")
    with open(prepare_path, "w") as f:
        f.write("\n".join(prepare_script_lines) + "\n")
    os.chmod(prepare_path, 0o755)

    # 4. Post-install script hook & timezone setup
    # NOTE: In mkosi v14 (Debian package), mkosi.postinst runs on the HOST with $BUILDROOT
    # pointing to the rootfs. We must chroot into $BUILDROOT to modify the target image.
    # Edge packages are installed by mkosi itself via [Content] Packages= after
    # mkosi.prepare.chroot adds custom APT repos.
    postinst_commands = []

    if recipe.timezone and recipe.timezone.strip():
        tz = recipe.timezone.strip()
        postinst_commands.append(f"ln -sf /usr/share/zoneinfo/{tz} /etc/localtime 2>/dev/null && echo \"{tz}\" > /etc/timezone 2>/dev/null || true")

    hostname_mac_script = """
# Auto-configure hostname to equal active network interface MAC address (strictly lowercase, no colons/delimiters)
IFACE=$(ip -4 route show default 2>/dev/null | awk '/default/ {print $5}' | head -n 1)
if [ -z "$IFACE" ]; then
  IFACE=$(ip -o link show 2>/dev/null | awk -F': ' '$2 != "lo" {print $2; exit}')
fi
if [ -n "$IFACE" ]; then
  MAC=$(cat /sys/class/net/$IFACE/address 2>/dev/null | tr -d ':' | tr '[:upper:]' '[:lower:]')
  if [ -n "$MAC" ]; then
    echo "Setting hostname to MAC address: $MAC (interface: $IFACE)"
    hostnamectl set-hostname "$MAC" 2>/dev/null || echo "$MAC" > /etc/hostname
    if [ -f /etc/hosts ]; then
      sed -i "s/127.0.1.1.*/127.0.1.1\t$MAC/g" /etc/hosts 2>/dev/null || true
    fi
  fi
fi
"""

    if recipe.hostname_from_netif:
        postinst_commands.append(hostname_mac_script)

    if recipe.raw_postinst and recipe.raw_postinst.strip():
        postinst_commands.append(recipe.raw_postinst.strip())

    # Clean formatted postinst commands
    postinst_body = "\n".join(postinst_commands) if postinst_commands else "echo '[POSTINST] Complete.'"

    postinst_script = f"""#!/bin/bash
set -e
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

ROOT="${{BUILDROOT:-/}}"

# Copy host DNS configuration into rootfs for chroot network access
cp -f /etc/resolv.conf "$ROOT/etc/resolv.conf" 2>/dev/null || true

# 1. Install pre-downloaded Edge platform .deb packages inside chroot
if [ -d "$ROOT/opt/edge_packages" ] && [ -n "$(ls -A "$ROOT/opt/edge_packages"/*.deb 2>/dev/null)" ]; then
  echo "[POSTINST] Installing pre-downloaded Edge platform packages via dpkg..."
  # Mount pseudo-filesystems for apt/dpkg to work correctly
  mount -t proc proc "$ROOT/proc" 2>/dev/null || true
  mount -t sysfs sys "$ROOT/sys" 2>/dev/null || true
  mount --bind /dev "$ROOT/dev" 2>/dev/null || true

  chroot "$ROOT" /bin/bash -c "
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\\$PATH
    ln -sf /bin/bash /bin/sh
    mkdir -p /opt/edge/venv/bin /opt/edge/bin /usr/bin
    if [ ! -f /opt/edge/venv/bin/python3.14 ]; then
      ln -sf /usr/bin/python3 /opt/edge/venv/bin/python3.14 2>/dev/null || true
      ln -sf /usr/bin/python3 /opt/edge/venv/bin/python3 2>/dev/null || true
      ln -sf /usr/bin/python3 /opt/edge/venv/bin/python 2>/dev/null || true
    fi

    if ! command -v apt-mark >/dev/null 2>&1; then
      echo '#!/bin/bash' > /usr/bin/apt-mark
      echo 'exit 0' >> /usr/bin/apt-mark
      chmod +x /usr/bin/apt-mark
    fi

    if [ ! -f /opt/edge/bin/ctrl-cli ] || [ ! -x /opt/edge/bin/ctrl-cli ]; then
      echo '#!/bin/bash' > /opt/edge/bin/ctrl-cli
      echo 'exit 0' >> /opt/edge/bin/ctrl-cli
      chmod +x /opt/edge/bin/ctrl-cli
    fi

    # 1. Unpack all deb packages without running postinst scripts
    dpkg --unpack --force-depends --force-overwrite /opt/edge_packages/*.deb || true

    # 2. Pre-create directories and files expected by edge-base postinst
    mkdir -p /etc/edge/webserver.0 /etc/edge /opt/edge/bin /opt/edge/venv/bin
    touch /etc/edge/webserver.0/htpasswd 2>/dev/null || true

    # 3. Fix bash double bracket syntax in autosdk script if present
    if [ -f /opt/edge/share/etc/environment.d/02-autosdk.sh ]; then
      sed -i 's/\\[\\[/\\[/g; s/\\]\\]/\\]/g' /opt/edge/share/etc/environment.d/02-autosdk.sh 2>/dev/null || true
    fi

    # 4. Convert strict 'set -e' to non-blocking 'set +e' in all postinst scripts for chroot build safety
    for pscript in /var/lib/dpkg/info/*.postinst /var/lib/dpkg/info/*.preinst; do
      if [ -f \"\\$pscript\" ]; then
        sed -i 's/^set -e/set +e/g' \"\\$pscript\" 2>/dev/null || true
        sed -i 's|/opt/edge/bin/ctrl-cli|/bin/true|g' \"\\$pscript\" 2>/dev/null || true
      fi
    done

    # 5. Overwrite ctrl-cli executable with a clean stub if it fails at runtime in chroot
    echo '#!/bin/bash' > /opt/edge/bin/ctrl-cli
    echo 'exit 0' >> /opt/edge/bin/ctrl-cli
    chmod +x /opt/edge/bin/ctrl-cli

    # 6. Fetch missing dependencies and configure all unpacked packages
    export DEBIAN_FRONTEND=noninteractive
    rm -f /etc/apt/apt.conf.d/*mkosi* /etc/apt/apt.conf.d/*cache* 2>/dev/null || true
    mkdir -p /var/cache/apt/archives/partial /var/lib/apt/lists/partial
    apt-get update --allow-insecure-repositories || true
    apt-get install -f -y --allow-unauthenticated || true
    dpkg --configure --pending --force-depends || true
  "

  # Unmount pseudo-filesystems
  umount "$ROOT/proc" 2>/dev/null || true
  umount "$ROOT/sys" 2>/dev/null || true
  umount -l "$ROOT/dev" 2>/dev/null || true

  rm -rf "$ROOT/opt/edge_packages"
fi

# 2. Run recipe post-install hooks (timezone, hostname MAC, custom scripts)
if [ "$ROOT" != "/" ] && [ -d "$ROOT/tmp" ]; then
  cat << 'HOOKEOF' > "$ROOT/tmp/recipe_postinst.sh"
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
{postinst_body}
HOOKEOF
  chmod +x "$ROOT/tmp/recipe_postinst.sh"
  chroot "$ROOT" /bin/bash /tmp/recipe_postinst.sh || true
  rm -f "$ROOT/tmp/recipe_postinst.sh"
else
  {postinst_body}
fi
# 3. Clean up non-Intel firmware, docs, locales, machine-id for ConditionFirstBoot, and APT caches from rootfs
echo "[POSTINST] Stripping non-Intel firmware, documentation, and uninitializing machine-id for firstboot..."
rm -f "$ROOT"/etc/machine-id || true
rm -rf "$ROOT"/usr/lib/firmware/nvidia* "$ROOT"/usr/lib/firmware/amdgpu* "$ROOT"/usr/lib/firmware/radeon* "$ROOT"/usr/lib/firmware/qcom* "$ROOT"/usr/lib/firmware/mellanox* "$ROOT"/usr/lib/firmware/mrvl* "$ROOT"/usr/lib/firmware/mediatek* "$ROOT"/usr/lib/firmware/broadcom* "$ROOT"/usr/lib/firmware/brcm* "$ROOT"/usr/lib/firmware/ath9k* "$ROOT"/usr/lib/firmware/ath10k* "$ROOT"/usr/lib/firmware/ath11k* "$ROOT"/usr/lib/firmware/ath12k* "$ROOT"/usr/lib/firmware/cxgb3* "$ROOT"/usr/lib/firmware/cxgb4* "$ROOT"/usr/lib/firmware/liquidio* "$ROOT"/usr/lib/firmware/netronome* "$ROOT"/usr/share/doc/* "$ROOT"/usr/share/man/* "$ROOT"/usr/share/info/* "$ROOT"/usr/share/help/* "$ROOT"/usr/share/gtk-doc/* "$ROOT"/usr/share/locale/* "$ROOT"/usr/share/sounds/* "$ROOT"/usr/share/icons/* || true

# 4. Ensure systemd-boot bootloader, vmlinuz, and initrd are prepared in /boot (ESP partition)
echo "[POSTINST] Initializing systemd-boot and copying kernel/initrd into /boot..."
if [ "$ROOT" != "/" ] && [ -d "$ROOT/tmp" ]; then
  # Re-mount pseudo-filesystems for bootctl and update-initramfs to work correctly
  mount -t proc proc "$ROOT/proc" 2>/dev/null || true
  mount -t sysfs sys "$ROOT/sys" 2>/dev/null || true
  mount --bind /dev "$ROOT/dev" 2>/dev/null || true
  mount -t devpts devpts "$ROOT/dev/pts" 2>/dev/null || true

  chroot "$ROOT" /bin/bash -c '
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
    bootctl install --no-variables 2>/dev/null || true
    KVER=$(ls /lib/modules 2>/dev/null | sort -V | tail -n1)

    # Ensure initramfs is generated with all required modules for VirtualBox/virtio
    if [ -n "$KVER" ] && command -v update-initramfs >/dev/null 2>&1; then
      echo "[POSTINST] Adding virtio modules to initramfs-tools/modules..."
      echo "virtio_blk" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "virtio_pci" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "virtio_net" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "virtio_scsi" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "virtio_console" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "vfat" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "fat" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "ext4" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "ahci" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "sd_mod" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "scsi_mod" >> /etc/initramfs-tools/modules 2>/dev/null || true
      echo "[POSTINST] Regenerating initramfs for kernel $KVER with virtio modules..."
      update-initramfs -u -k "$KVER" || true
    fi

    for f in /boot/vmlinuz-$KVER /boot/vmlinuz* /vmlinuz*; do
      if [ -f "$f" ] && [ "$f" != "/boot/vmlinuz" ]; then
        cp -f "$f" /boot/vmlinuz 2>/dev/null || true
        break
      fi
    done
    for f in /boot/initrd.img-$KVER /boot/initrd* /boot/initramfs* /initrd* /initramfs*; do
      if [ -f "$f" ] && [ "$f" != "/boot/initrd.img" ]; then
        cp -f "$f" /boot/initrd.img 2>/dev/null || true
        break
      fi
    done
    mkdir -p /boot/loader/entries
    echo "default edge.conf" > /boot/loader/loader.conf
    echo "timeout 3" >> /boot/loader/loader.conf
    echo "console-mode max" >> /boot/loader/loader.conf
    echo "title Edge OS" > /boot/loader/entries/edge.conf
    echo "linux /vmlinuz" >> /boot/loader/entries/edge.conf
    echo "initrd /initrd.img" >> /boot/loader/entries/edge.conf
    echo "options root=LABEL=edgeroot rw quiet loglevel=3 fsck.mode=skip console=tty0 console=ttyS0,115200 ipv6.disable=1 nohz=off" >> /boot/loader/entries/edge.conf
  ' || true

  # Unmount pseudo-filesystems
  umount "$ROOT/dev/pts" 2>/dev/null || true
  umount "$ROOT/proc" 2>/dev/null || true
  umount "$ROOT/sys" 2>/dev/null || true
  umount -l "$ROOT/dev" 2>/dev/null || true
fi
"""
    for hk in ["mkosi.postinst", "mkosi.finalize"]:
        postinst_path = os.path.join(workspace_path, hk)
        with open(postinst_path, "w") as f:
            f.write(postinst_script)
        os.chmod(postinst_path, 0o755)

    # 5. Firstboot script & systemd service
    firstboot_lines = ["#!/bin/bash", "set -e"]

    if recipe.hostname_from_netif:
        firstboot_lines.append(hostname_mac_script)

    if recipe.raw_firstboot and recipe.raw_firstboot.strip():
        firstboot_lines.append(recipe.raw_firstboot.strip())

    if len(firstboot_lines) > 2:
        fb_bin_dir = os.path.join(extra_dir, "opt", "edge", "bin")
        os.makedirs(fb_bin_dir, exist_ok=True)
        fb_script_path = os.path.join(fb_bin_dir, "firstboot.sh")
        with open(fb_script_path, "w") as f:
            f.write("\n".join(firstboot_lines) + "\n")
        os.chmod(fb_script_path, 0o755)

        systemd_dir = os.path.join(extra_dir, "etc", "systemd", "system")
        os.makedirs(systemd_dir, exist_ok=True)
        fb_svc_path = os.path.join(systemd_dir, "edge-firstboot.service")
        with open(fb_svc_path, "w") as f:
            f.write("""[Unit]
Description=Edge Firstboot Initialization Service
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/opt/edge/bin/firstboot.sh
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
""")

        wants_dir = os.path.join(extra_dir, "etc", "systemd", "system", "multi-user.target.wants")
        os.makedirs(wants_dir, exist_ok=True)
        link_path = os.path.join(wants_dir, "edge-firstboot.service")
        if not os.path.exists(link_path):
            try:
                os.symlink("/etc/systemd/system/edge-firstboot.service", link_path)
            except Exception:
                pass

    # 6. Debian Preseed file
    if recipe.raw_preseed_cfg and recipe.raw_preseed_cfg.strip():
        preseed_path = os.path.join(workspace_path, "preseed.cfg")
        with open(preseed_path, "w") as f:
            f.write(recipe.raw_preseed_cfg.strip() + "\n")


def cleanup_workspace(recipe_id: int):
    """
    Removes workspace directory for a deleted recipe.
    """
    base_dir = os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace")
    recipe_ws = os.path.join(base_dir, str(recipe_id))
    if os.path.exists(recipe_ws):
        shutil.rmtree(recipe_ws, ignore_errors=True)