import os
import re
import shlex
import shutil
import urllib.error
import urllib.request
from typing import Dict, List, Tuple
from models import Recipe, RecipeAsset
from core.netnames import DEFAULT_START_INDEX, STAMP_PATH as NETNAMES_STAMP, rename_script
from core.packages import (
    ARMBIAN_KEYRING_PATH,
    ARMBIAN_REPO_URL,
    armbian_source_line,
    board_console,
    board_dtb,
    board_key,
    is_armbian,
)
from core.rk3588 import provision_script

# Static fallback so glibc getaddrinfo resolves DNS before networkd/DHCP has
# handed out anything (this image ships no systemd-resolved, so nothing else
# ever rewrites /etc/resolv.conf after boot). Written into the image twice:
# once as the shipped file (see FALLBACK_RESOLV_CONF usage below) and again
# at the very end of mkosi.postinst, because postinst temporarily overwrites
# it with the *build host's* resolv.conf to give its own chroot steps network
# access, and a container's resolv.conf (e.g. Docker's 127.0.0.11) is
# meaningless once baked onto real hardware.
FALLBACK_RESOLV_CONF = (
    "# Generated by D.U.R.O. image builder\n"
    "nameserver 77.88.8.8\n"
    "nameserver 8.8.8.8\n"
    "nameserver 1.1.1.1\n"
)

# Firmware blobs a board's drivers ask for by name and that neither Debian nor
# Ubuntu ships outside the ~655 MB "linux-firmware" package. Fetching that
# whole .deb during postinst (even with a persistent apt cache) proved too
# slow and unreliable on this network -- one build spent 2.5 minutes before a
# mirror reset the connection. gitlab.com is the canonical upstream project
# for these exact files and serves them directly, so they are fetched here (at
# prepare time, in Python, with real internet access) instead of through
# apt/dpkg in the build chroot. git.kernel.org mirrors the same repo but was
# tested and rejected: it returns 403 to Python's default urllib UA and an
# HTML challenge page (still HTTP 200) to a browser-like one, either of which
# would silently ship as "firmware" without the per-file magic check below.
#
#   rtl_nic/rtl8125b-2.fw -- r8169 cannot bring the on-board 2.5GbE NICs up at
#     full capability without it ("Unable to load firmware", seen live on
#     hardware); the link still comes up, just degraded.
#   rockchip/dptx.bin -- the DisplayPort controller the rockchipdrm driver
#     drives for the board's two USB-C DP outputs. update-initramfs flagged it
#     on every build ("Possible missing firmware ... for built-in driver
#     rockchipdrm"); without it those outputs stay dark.
_FIRMWARE_BASE_URL = "https://gitlab.com/kernel-firmware/linux-firmware/-/raw/main/"

# board -> ((path under /lib/firmware, first bytes of a genuine file), ...)
_BOARD_FIRMWARE: Dict[str, Tuple[Tuple[str, bytes], ...]] = {
    "opi5-plus": (
        ("rtl_nic/rtl8125b-2.fw", b"\x00\x00\x00\x00"),
        ("rockchip/dptx.bin", b"\x10\x80\x01\x00"),
    ),
}


def _fetch_board_firmware(workspace_path: str, board: str) -> None:
    # Both trees, on purpose. mkosi.skeleton is copied in before packages are
    # installed, so update-initramfs -- which the kernel package triggers
    # during its own configuration, long before extra trees exist -- can see
    # the blobs; with only mkosi.extra it still reported "Possible missing
    # firmware ... for built-in driver" and built an initrd without them.
    # mkosi.extra is copied in last and is what guarantees the files survive
    # into the finished image whatever the packages did in between.
    # skeleton uses usr/lib/ rather than lib/: it lands before the base system
    # exists, and creating a real /lib directory there would shadow the
    # merged-usr symlink the distro expects.
    dests = [
        os.path.join(workspace_path, "mkosi.skeleton", "usr", "lib", "firmware"),
        os.path.join(workspace_path, "mkosi.extra", "lib", "firmware"),
    ]
    wanted = dict(_BOARD_FIRMWARE.get(board, ()))

    # Workspaces are reused. A recipe retargeted at another board (or off
    # armbian entirely) would otherwise keep shipping the previous board's
    # blobs, which is how a "generic" image ends up carrying firmware for
    # silicon it does not have.
    for entries in _BOARD_FIRMWARE.values():
        for rel_path, _magic in entries:
            if rel_path in wanted:
                continue
            for fw_root in dests:
                stale = os.path.join(fw_root, *rel_path.split("/"))
                if os.path.exists(stale):
                    os.remove(stale)

    for rel_path, magic in wanted.items():
        for fw_root in dests:
            _fetch_firmware_file(fw_root, rel_path, magic)


def _fetch_firmware_file(firmware_dir: str, rel_path: str, magic: bytes) -> None:
    dest = os.path.join(firmware_dir, *rel_path.split("/"))
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        return

    name = rel_path.rsplit("/", 1)[-1]

    # Shared across every recipe/build (not the per-recipe workspace_path),
    # same convention as PackageCacheDirectory in mkosi_config.py -- these
    # files never change per-recipe, so there is no reason to refetch one
    # once any build has already pulled a copy.
    cache_dir = os.path.join(os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace"), "fwcache")
    cached = os.path.join(cache_dir, name)
    url = _FIRMWARE_BASE_URL + rel_path

    if not (os.path.exists(cached) and os.path.getsize(cached) > 0):
        try:
            with urllib.request.urlopen(urllib.request.Request(url), timeout=30) as resp:
                data = resp.read()
        except (urllib.error.URLError, OSError) as exc:
            print(f"[WARNING] Could not fetch {name} from {url}: {exc}")
            return

        if not data.startswith(magic):
            print(f"[WARNING] {name} download did not look like firmware (wrong content, possibly an HTML error page) -- discarded")
            return

        os.makedirs(cache_dir, exist_ok=True)
        with open(cached, "wb") as f:
            f.write(data)

    os.makedirs(os.path.dirname(dest), exist_ok=True)
    shutil.copy2(cached, dest)


# apt.armbian.com signs its indices, but nothing shipped the public key, so
# every apt that saw the repo -- mkosi's own, the build chroot's, and the one
# on the finished board -- reported "The signatures couldn't be verified
# because no keyring is specified" and only proceeded thanks to [trusted=yes].
# The key is armoured ASCII; apt reads .asc from trusted.gpg.d as-is, so there
# is no gpg --dearmor step here.
# The RK3588 flow clones the card to NVMe with dd, and dd copies every
# identifier a filesystem or a partition table carries: the label, the
# filesystem UUID and the PARTUUID come out identical on both media. Verified
# on hardware after a provisioning run -- all three matched byte for byte. So
# "root=LABEL=edgeroot" has two answers on a provisioned board, and the kernel
# takes whichever blkid returns first: a freshly written test card booted the
# installed system instead of itself, looking for all the world like the build
# had shipped stale content.
#
# The way out is for each medium to name a root nothing else can answer to.
# The image gets this fixed PARTUUID (pinned in the repart config so it is
# known while the loader entry is being written), and provisioning hands the
# clone a fresh random one plus a matching loader entry -- see
# edge_rk3588_reidentify in core/rk3588.py. Labels are left exactly as they
# are: the platform on the installed system depends on them.
IMAGE_ROOT_PARTUUID = "ed9e0001-0000-4000-8000-000000000001"

_ARMBIAN_KEY_URL = "https://apt.armbian.com/armbian.key"
_ARMBIAN_KEY_HEADER = b"-----BEGIN PGP PUBLIC KEY BLOCK-----"


def install_armbian_key(workspace_path: str) -> bool:
    """
    Places the Armbian repo signing key into every apt tree of the workspace.

    Returns True when the key is in place, so callers can emit a signed-by=
    source line; False leaves them on the [trusted=yes] fallback. A build must
    never fail just because this fetch did not go through.
    """
    trees = ["mkosi.sandbox", "mkosi.skeleton", "mkosi.extra"]
    dests = [
        os.path.join(workspace_path, t, "etc", "apt", "trusted.gpg.d", "armbian.asc")
        for t in trees
    ]

    cache_dir = os.path.join(os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace"), "fwcache")
    cached = os.path.join(cache_dir, "armbian.asc")

    if not (os.path.exists(cached) and os.path.getsize(cached) > 0):
        try:
            with urllib.request.urlopen(urllib.request.Request(_ARMBIAN_KEY_URL), timeout=15) as resp:
                data = resp.read()
        except (urllib.error.URLError, OSError) as exc:
            print(f"[WARNING] Could not fetch the Armbian repo key from {_ARMBIAN_KEY_URL}: {exc}")
            return False

        if not data.startswith(_ARMBIAN_KEY_HEADER):
            print("[WARNING] Armbian repo key download was not an armoured PGP key -- discarded")
            return False

        os.makedirs(cache_dir, exist_ok=True)
        with open(cached, "wb") as f:
            f.write(data)

    for dest in dests:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        shutil.copy2(cached, dest)
    return True


def armbian_key_installed(workspace_path: str) -> bool:
    """Whether install_armbian_key() has already put the key in this workspace."""
    key = os.path.join(workspace_path, "mkosi.extra", "etc", "apt", "trusted.gpg.d", "armbian.asc")
    return os.path.exists(key) and os.path.getsize(key) > 0


def prepare_workspace(recipe_id: int, recipe: Recipe = None) -> str:
    """
    Creates isolated workspace directory structure for mkosi build.
    """
    base_dir = os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace")
    recipe_ws = os.path.join(base_dir, str(recipe_id))

    subdirs = [
        "output",
        "assets",
        "gpg_keys",
        "mkosi.extra/etc/apt/sources.list.d",
        "mkosi.extra/etc/apt/trusted.gpg.d",
        "mkosi.extra/root/.ssh",
        "mkosi.extra/etc/network/interfaces.d",
        "mkosi.extra/etc/initramfs-tools",
        "mkosi.extra/opt/custom",
        # mkosi.conf declares SkeletonTrees=mkosi.skeleton unconditionally, and
        # mkosi aborts with "mkosi.skeleton does not exist" when the directory
        # is absent. populate_extra_tree only creates it for recipes that have
        # custom APT repositories, so a recipe without any never built.
        "mkosi.skeleton/etc/apt/sources.list.d",
        # mkosi.extra/etc/apt/trusted.gpg.d above is too late for this: the
        # mkosi.prepare script's "apt-get update" for the custom repo runs
        # right after packages are installed, well before mkosi.extra is
        # copied in. Without the directory existing yet, apt logs "W: OpenPGP
        # signature verification failed: ... List of files can't be created
        # as '/etc/apt/trusted.gpg.d/' is not a directory" for every repo on
        # every build -- harmless with a [trusted=yes] source (apt still
        # trusts it), but real noise, and would matter for a signed one.
        "mkosi.skeleton/etc/apt/trusted.gpg.d",
    ]

    # Clean stale hook scripts from previous runs
    for old_hook in ["mkosi.postinst", "mkosi.postinst.chroot", "mkosi.finalize", "mkosi.finalize.chroot", "mkosi.prepare", "mkosi.prepare.chroot"]:
        old_h_path = os.path.join(recipe_ws, old_hook)
        if os.path.exists(old_h_path):
            try:
                os.remove(old_h_path)
            except Exception:
                pass

    for d in subdirs:
        os.makedirs(os.path.join(recipe_ws, d), exist_ok=True)

    # Ensure initramfs-tools includes ISO9660 and CD-ROM modules in generated initrd
    initramfs_modules_file = os.path.join(recipe_ws, "mkosi.extra/etc/initramfs-tools/modules")
    with open(initramfs_modules_file, "w") as f:
        f.write("# Required storage & filesystem kernel modules for Edge OS Installer\n"
                "isofs\nsr_mod\ncdrom\nvfat\next4\nsd_mod\nahci\nloop\noverlay\n")

    repart_dir = os.path.join(recipe_ws, "mkosi.repart")
    if os.path.exists(repart_dir):
        shutil.rmtree(repart_dir, ignore_errors=True)
    os.makedirs(repart_dir, exist_ok=True)

    partitions = (recipe.partitions if (recipe and recipe.partitions) else None) or [
        {"mountpoint": "/boot", "size": "512M", "filesystem": "vfat", "type": "esp", "label": "edgeboot"},
        {"mountpoint": "/", "size": "2G", "filesystem": "ext4", "type": "root", "label": "edgeroot"},
        {"mountpoint": "/var/log/edge", "size": "1G", "filesystem": "ext4", "type": "generic", "label": "edgelog"},
        {"mountpoint": "/var/opt/edge", "size": "max", "filesystem": "ext4", "type": "generic", "label": "edgestor"},
    ]

    # BootROM RK3588 читает загрузчик по фиксированным смещениям в начале
    # носителя: idbloader.img с сектора 64, u-boot.itb с сектора 16384. Раздел
    # по умолчанию начинается с сектора 2048, то есть u-boot.itb лёг бы поверх
    # файловой системы -- образ собирается, но плата с него не стартует.
    # Пустой неформатируемый раздел на 16 МБ занимает секторы 2048..34815 и
    # накрывает собой оба смещения; idbloader попадает в штатный зазор GPT до
    # 2048. Та же раскладка у собственных образов Armbian.
    if recipe and is_armbian(recipe.distribution):
        with open(os.path.join(repart_dir, "00-rk3588-loader.conf"), "w") as f:
            f.write(
                "[Partition]\n"
                "Type=linux-generic\n"
                "Label=rkloader\n"
                "SizeMinBytes=16M\n"
                "SizeMaxBytes=16M\n"
            )

    for idx, p in enumerate(partitions, start=1):
        p_type = (p.get("type") or "generic").lower()
        p_fs = (p.get("filesystem") or "ext4").lower()
        p_size = str(p.get("size") or "2G")
        p_mount = p.get("mountpoint") or "/"
        p_label = p.get("label") or f"part{idx}"

        conf_filename = f"{idx * 10:02d}-{p_type}-{p_label}.conf"
        conf_path = os.path.join(repart_dir, conf_filename)

        lines = ["[Partition]"]
        if p_type == "esp":
            lines.append("Type=esp")
            lines.append("Format=vfat")
            lines.append("CopyFiles=/boot:/")
        elif p_type == "root":
            lines.append("Type=root")
            lines.append(f"Format={p_fs}")
            lines.append("CopyFiles=/")
            # Размер root задаётся потолком, а не полом: repart ужимает раздел
            # под фактически скопированное. Пол в 8G раздувал распакованный .raw
            # до ~10 ГБ независимо от того, что реально попало в образ, и ровно
            # столько же потом ехало по dd на NVMe. Тот же Minimize=guess стоит
            # в дефолтной разметке самого mkosi.
            lines.append("Minimize=guess")
            # Pinned so postinst can name it on the kernel command line: the
            # PARTUUID repart would otherwise assign is only known after the
            # image is assembled, long after the loader entry is written.
            # See IMAGE_ROOT_PARTUUID for why the boot has to key on it.
            if recipe and is_armbian(recipe.distribution):
                lines.append(f"UUID={IMAGE_ROOT_PARTUUID}")
        elif p_type == "swap":
            lines.append("Type=swap")
            lines.append("Format=swap")
        else:
            lines.append("Type=linux-generic")
            lines.append(f"Format={p_fs}")
            if p_mount and p_mount != "/":
                lines.append(f"CopyFiles={p_mount}")
                # The directory has to exist in the rootfs for two reasons:
                # repart reads it as the CopyFiles= source and otherwise logs
                # "Failed to open source file '/buildroot/...', skipping", and
                # the same path is the fstab mount point on the running board.
                # Nothing else in the build creates it -- for a recipe whose
                # packages never touch /var/opt/edge it simply was not there.
                os.makedirs(
                    os.path.join(recipe_ws, "mkosi.extra", p_mount.lstrip("/")),
                    exist_ok=True,
                )

        if p_label:
            lines.append(f"Label={p_label}")

        if p_size and p_size.lower() not in ["max", "100%", "auto"]:
            size_val = p_size.upper()
            if not size_val.endswith("M") and not size_val.endswith("G") and not size_val.endswith("B"):
                size_val += "M"
            # Для root размер -- потолок (см. Minimize=guess выше): если
            # содержимое в него не влезет, сборка упадёт, а не молча обрежет
            # rootfs. Для остальных разделов это по-прежнему гарантированный
            # минимум, которым управляет сам рецепт.
            lines.append(f"SizeMaxBytes={size_val}" if p_type == "root" else f"SizeMinBytes={size_val}")

        with open(conf_path, "w") as f:
            f.write("\n".join(lines) + "\n")

    rel = (recipe.release if recipe else "bookworm") or "bookworm"
    cache_base = os.path.join(base_dir, "cache")
    os.makedirs(os.path.join(cache_base, "apt", "partial"), exist_ok=True)
    os.makedirs(os.path.join(cache_base, f"apt_{rel}", "partial"), exist_ok=True)
    if os.path.exists(cache_base):
        for item in os.listdir(cache_base):
            if item.startswith("apt"):
                os.makedirs(os.path.join(cache_base, item, "partial"), exist_ok=True)

    return recipe_ws


def populate_extra_tree(recipe: Recipe, assets: List[RecipeAsset], workspace_path: str,
                        skip_repo_urls=frozenset()):
    """
    Populates mkosi.extra/ overlay tree with SSH keys, custom APT repositories, assets, postinst, firstboot, and preseed files.
    """
    extra_dir = os.path.join(workspace_path, "mkosi.extra")

    # 1. SSH Keys & Custom SSH Port
    if recipe.ssh_keys:
        ssh_dir = os.path.join(extra_dir, "root", ".ssh")
        os.makedirs(ssh_dir, exist_ok=True)
        auth_keys_path = os.path.join(ssh_dir, "authorized_keys")
        with open(auth_keys_path, "w") as f:
            f.write("\n".join(recipe.ssh_keys) + "\n")

    ssh_port = getattr(recipe, 'ssh_port', 2222) or 2222
    sshd_conf_dir = os.path.join(extra_dir, "etc", "ssh", "sshd_config.d")
    os.makedirs(sshd_conf_dir, exist_ok=True)

    # Без явных директив образ живёт на умолчаниях дистрибутива, а у Debian и
    # Ubuntu PermitRootLogin по умолчанию prohibit-password -- заданный в
    # рецепте пароль root молча не работал бы по SSH. Пишем оба решения явно,
    # чтобы образ вёл себя одинаково независимо от базы.
    pw_auth = getattr(recipe, "ssh_password_auth", True)
    root_pw = getattr(recipe, "ssh_permit_root_login", False)
    sshd_lines = [
        f"Port {ssh_port}",
        f"PasswordAuthentication {'yes' if pw_auth else 'no'}",
        # Запрет касается только пароля: вход root по ключу остаётся возможен,
        # иначе образ без пользователей стал бы недоступен вовсе.
        f"PermitRootLogin {'yes' if root_pw else 'prohibit-password'}",
    ]
    with open(os.path.join(sshd_conf_dir, "edge.conf"), "w") as f:
        f.write("\n".join(sshd_lines) + "\n")

    # Воркспейс переиспользуется между сборками: файл от прошлой версии остался
    # бы в образе и переопределял бы Port по алфавиту после edge.conf.
    stale_port_conf = os.path.join(sshd_conf_dir, "port.conf")
    if os.path.exists(stale_port_conf):
        os.remove(stale_port_conf)

    # systemd ssh.socket drop-in for socket-activated sshd
    ssh_sock_dir = os.path.join(extra_dir, "etc", "systemd", "system", "ssh.socket.d")
    os.makedirs(ssh_sock_dir, exist_ok=True)
    with open(os.path.join(ssh_sock_dir, "port.conf"), "w") as f:
        f.write(f"[Socket]\nListenStream=\nListenStream={ssh_port}\n")

    # 1.5. Static Hostname Overlay and /etc/fstab
    etc_dir = os.path.join(extra_dir, "etc")
    os.makedirs(etc_dir, exist_ok=True)
    if recipe.hostname:
        with open(os.path.join(etc_dir, "hostname"), "w") as f:
            f.write(recipe.hostname.strip().lower() + "\n")
        # A minimal mkosi image ships no /etc/hosts at all -- that convention
        # comes from debian-installer, not from the base packages. Without it,
        # nothing resolves the hostname to localhost, and every "sudo"
        # invocation prints "unable to resolve host <name>" -- harmless, but on
        # every single command. hostname_from_netif rewrites this line again at
        # runtime once the MAC-derived name is known (see hostname_mac_script).
        with open(os.path.join(etc_dir, "hosts"), "w") as f:
            f.write(
                "127.0.0.1\tlocalhost\n"
                f"127.0.1.1\t{recipe.hostname.strip().lower()}\n\n"
                "::1\t\tlocalhost ip6-localhost ip6-loopback\n"
                "ff02::1\t\tip6-allnodes\n"
                "ff02::2\t\tip6-allrouters\n"
            )

    fstab_lines = [
        "# /etc/fstab: generated by D.U.R.O. image builder",
        "LABEL=edgeroot    /               ext4    defaults,rw          0    1",
        "LABEL=edgelog     /var/log/edge   ext4    defaults,nofail      0    2",
        "LABEL=edgestor    /var/opt/edge   ext4    defaults,nofail      0    2",
    ]
    with open(os.path.join(etc_dir, "fstab"), "w") as f:
        f.write("\n".join(fstab_lines) + "\n")

    # 1.6. Network configuration (systemd-networkd).
    # Without this the image ships no .network file matching a physical NIC, so
    # systemd-networkd (which is enabled but has nothing to manage) leaves the
    # interface DOWN and the machine has no network at all. The old simple-cdd
    # flow got this for free from debian-installer's netcfg, which has no
    # equivalent in the mkosi pipeline.
    #
    # The default Name= glob deliberately covers both the Debian-style eth0 and
    # the Ubuntu/systemd predictable enp0s3 naming, so one recipe works on both
    # distributions without knowing the NIC name at build time.
    net_dir = os.path.join(extra_dir, "etc", "systemd", "network")
    os.makedirs(net_dir, exist_ok=True)

    # systemd-networkd-wait-online waits for EVERY managed link by default. The
    # board has two on-board NICs and normally only one is patched, so the
    # service sat in "activating" until its 120 s timeout on every single boot,
    # holding network-online.target down with it -- and with it everything
    # ordered after that target. Measured on hardware: edge-firstboot.service
    # (hostname, interface naming, and the NVMe clone, none of which need the
    # network at all) did not start until two minutes into the boot. --any
    # releases the target as soon as one link is up, which is the condition
    # that actually matters here.
    wait_online_dir = os.path.join(
        extra_dir, "etc", "systemd", "system", "systemd-networkd-wait-online.service.d"
    )
    os.makedirs(wait_online_dir, exist_ok=True)
    with open(os.path.join(wait_online_dir, "10-edge-any-interface.conf"), "w") as f:
        f.write(
            "[Service]\n"
            "ExecStart=\n"
            "ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any\n"
        )

    net_cfg = recipe.network_config if isinstance(recipe.network_config, dict) else {}

    # Interfaces are renamed to <prefix>N on the running system, and "en*"
    # does not cover "edge0". Without the prefix in the glob, an image that has
    # no edge-netconf (where .network files are written per MAC) would be left
    # after the rename with no matching .network at all -- and therefore with
    # no address.
    _rename_prefix = net_cfg.get("prefix")
    default_match = f"en* eth* {_rename_prefix}*" if _rename_prefix else "en* eth*"

    net_ifaces = net_cfg.get("interfaces")
    if not isinstance(net_ifaces, list) or not net_ifaces:
        net_ifaces = [{"match": default_match, "dhcp": True}]

    for idx, iface in enumerate(net_ifaces, start=1):
        if not isinstance(iface, dict):
            continue
        match = iface.get("name") or iface.get("match") or default_match
        lines = ["# Generated by D.U.R.O. image builder", "[Match]", f"Name={match}", "", "[Network]"]

        address = iface.get("address")
        use_dhcp = iface.get("dhcp", not address)
        if use_dhcp:
            lines.append("DHCP=yes")
        if address:
            # Accept either "10.0.0.5/24" or a bare address plus prefix/netmask.
            if "/" not in str(address):
                prefix = iface.get("prefix") or iface.get("netmask") or "24"
                address = f"{address}/{prefix}"
            lines.append(f"Address={address}")
        if iface.get("gateway"):
            lines.append(f"Gateway={iface['gateway']}")
        dns = iface.get("dns")
        if isinstance(dns, str):
            dns = [dns]
        if not dns or not isinstance(dns, list) or not any(dns):
            dns = ["77.88.8.8", "8.8.8.8", "1.1.1.1"]
        for server in dns:
            if server:
                lines.append(f"DNS={server}")

        # systemd-networkd applies the FIRST .network file (lexicographic order)
        # whose [Match] matches, so a catch-all glob must sort AFTER explicit
        # interface names -- otherwise "en* eth*" shadows every specific static
        # config that follows it and those NICs silently fall back to DHCP.
        safe = re.sub(r'[^A-Za-z0-9]+', '-', str(match)).strip('-') or f"if{idx}"
        prio = 70 + idx if any(c in str(match) for c in "*?[") else 10 + idx
        conf_name = f"{prio}-edge-{safe}.network"
        with open(os.path.join(net_dir, conf_name), "w") as f:
            f.write("\n".join(lines) + "\n")

    # Generate fallback /etc/resolv.conf so glibc getaddrinfo resolves DNS even before networkd/resolved initializes
    resolv_path = os.path.join(extra_dir, "etc", "resolv.conf")
    os.makedirs(os.path.dirname(resolv_path), exist_ok=True)
    if not os.path.exists(resolv_path) or os.path.getsize(resolv_path) == 0:
        with open(resolv_path, "w") as f:
            f.write(FALLBACK_RESOLV_CONF)

    # Board-specific hardware fixes are gated on board_key(), never on
    # is_armbian() alone: a fix for one board's silicon has no reason to
    # apply to a different RK3588 board that may not even carry the same
    # chip. See the "hardware-board-fixes" skill for the pattern this follows.
    _fetch_board_firmware(
        workspace_path,
        board_key(getattr(recipe, "board", None)) if is_armbian(recipe.distribution) else "",
    )

    # 2. Custom APT Repositories (Populated into both mkosi.skeleton and mkosi.extra)
    rel = recipe.release or "bookworm"
    repo_lines = []
    if recipe.repositories and isinstance(recipe.repositories, list):
        for repo in recipe.repositories:
            if isinstance(repo, dict) and repo.get("url"):
                url = repo.get("url")
                # A repository that publishes nothing for this architecture is
                # left out: shipping it would make `apt update` on the device
                # fail with 404 on every run, forever.
                if url in skip_repo_urls:
                    continue
                suite = repo.get("suite") or rel
                comp = repo.get("components") or "main"
                repo_lines.append(f"deb [trusted=yes] {url} {suite} {comp}")
    user_repo_lines = list(repo_lines)

    # Ядро, DTB и U-Boot платы живут только в репозитории Armbian, и apt должен
    # видеть его ещё во время сборки. Для этого годится только mkosi.sandbox:
    # mkosi запускает пакетный менеджер СНАРУЖИ образа, поэтому его конфигурация
    # из mkosi.skeleton (которая уезжает в /buildroot) на установку не влияет --
    # ровно этим и объяснялось "Unable to locate package linux-image-vendor-rk35xx"
    # при том, что предполётная проверка те же пакеты в индексе находила.
    # Каталог mkosi.sandbox/ подхватывается автоматически, без строки в конфиге.
    # postinst ядра Armbian сразу дёргает update-initramfs, и делает это под
    # `set -e`: падение хука роняет весь пакет и всю сборку. А mkinitramfs
    # читает /etc/initramfs-tools/initramfs.conf, который лежит в conffile'ах
    # initramfs-tools-core -- dpkg кладёт conffile'ы не при распаковке, а при
    # конфигурации пакета. С флагами mkosi (--force-depends,
    # APT::Immediate-Configure=off) initramfs-tools успевает сконфигурироваться
    # раньше собственной зависимости initramfs-tools-core, ядро идёт следом --
    # и получает "cannot open /etc/initramfs-tools/initramfs.conf".
    # Файл из mkosi.skeleton попадает в /buildroot ДО установки пакетов, поэтому
    # хук отрабатывает при любом порядке конфигурации. Содержимое -- штатные
    # значения самого initramfs-tools-core, так что образ получает ровно то, что
    # положил бы пакет. Свой initramfs edge-duro всё равно пересобирает позже в
    # postinst.
    if is_armbian(recipe.distribution):
        initramfs_dir = os.path.join(workspace_path, "mkosi.skeleton", "etc", "initramfs-tools")
        os.makedirs(os.path.join(initramfs_dir, "conf.d"), exist_ok=True)
        with open(os.path.join(initramfs_dir, "initramfs.conf"), "w") as f:
            f.write(
                "MODULES=most\n"
                "BUSYBOX=auto\n"
                "COMPRESS=zstd\n"
                "DEVICE=\n"
                "NFSROOT=auto\n"
                "RUNSIZE=10%\n"
                "FSTYPE=auto\n"
            )

    # initramfs собирался трижды за сборку -- postinst ядра, второй триггер
    # dpkg и наш явный проход в postinst, -- по 32-37 секунд каждый, суммарно
    # больше 40% времени сборки. mkinitramfs почти целиком однопоточный, из-за
    # чего загрузка хоста выглядела как "процессор простаивает, а сборка идёт
    # вечность". Пакетам генерировать нечего: набор модулей и компрессор
    # доопределяются позже, поэтому на время установки генерация выключается,
    # а postinst удаляет этот файл и делает единственный проход.
    initramfs_skel = os.path.join(workspace_path, "mkosi.skeleton", "etc", "initramfs-tools")
    os.makedirs(initramfs_skel, exist_ok=True)
    with open(os.path.join(initramfs_skel, "update-initramfs.conf"), "w") as f:
        f.write("update_initramfs=no\n")

    sandbox_sources = os.path.join(
        workspace_path, "mkosi.sandbox", "etc", "apt", "sources.list.d"
    )
    sandbox_armbian = os.path.join(sandbox_sources, "armbian.list")
    if is_armbian(recipe.distribution) and ARMBIAN_REPO_URL not in skip_repo_urls:
        os.makedirs(sandbox_sources, exist_ok=True)
        signed_by = ARMBIAN_KEYRING_PATH if install_armbian_key(workspace_path) else ""
        with open(sandbox_armbian, "w") as f:
            f.write(armbian_source_line(rel, signed_by) + "\n")
        # mkosi's own "Syncing package manager metadata" step runs apt-get
        # against mkosi.sandbox before anything else -- before mkosi.skeleton
        # is even copied in, so putting this directory there instead (as
        # elsewhere in this function) would be too late for this specific
        # sync. Without it apt logs "W: OpenPGP signature verification
        # failed: ... List of files can't be created as
        # '/etc/apt/trusted.gpg.d/' is not a directory" on every build --
        # harmless with [trusted=yes] (apt still proceeds), but real noise.
        os.makedirs(os.path.join(workspace_path, "mkosi.sandbox", "etc", "apt", "trusted.gpg.d"), exist_ok=True)
        # В сам образ репозиторий тоже нужен: иначе apt update на плате его не
        # знает и обновления ядра приходить перестанут.
        repo_lines.insert(0, armbian_source_line(rel, signed_by))

        # initramfs.conf выше подложен до установки пакетов, поэтому dpkg видит
        # "существующий, но никем не заявленный" conffile и по умолчанию
        # спрашивает, чью версию оставить. Stdin в сборке нет -- вопрос сразу
        # валит пакет: "end of file on stdin at conffile prompt". Эти два флага
        # отвечают за нас, не заводя интерактива. Файл кладётся в mkosi.sandbox:
        # пакетный менеджер mkosi запускает снаружи образа, свой dpkg.cfg.d он
        # читает оттуда же.
        sandbox_dpkg = os.path.join(workspace_path, "mkosi.sandbox", "etc", "dpkg", "dpkg.cfg.d")
        os.makedirs(sandbox_dpkg, exist_ok=True)
        with open(os.path.join(sandbox_dpkg, "edge-noninteractive"), "w") as f:
            f.write("force-confdef\nforce-confold\n")
    else:
        # Воркспейс переиспользуется: рецепт, уведённый с Armbian, иначе
        # продолжил бы собираться с чужим репозиторием и чужими флагами dpkg.
        for stale in (
            sandbox_armbian,
            os.path.join(workspace_path, "mkosi.sandbox", "etc", "dpkg",
                         "dpkg.cfg.d", "edge-noninteractive"),
            os.path.join(workspace_path, "mkosi.skeleton", "etc",
                         "initramfs-tools", "initramfs.conf"),
            *[
                os.path.join(workspace_path, t, "etc", "apt", "trusted.gpg.d", "armbian.asc")
                for t in ("mkosi.sandbox", "mkosi.skeleton", "mkosi.extra")
            ],
        ):
            if os.path.exists(stale):
                os.remove(stale)

    # mkosi.sandbox gets the user's repositories but NOT the Armbian one: that
    # already has its own armbian.list there, and listing a source twice makes
    # apt warn about the target being configured multiple times. Without this
    # tree, a repository added in the recipe UI reached only the build chroot
    # and the finished image -- never mkosi's own package manager, which runs
    # outside the image and is what actually installs the recipe's packages.
    # Exactly the failure that "Unable to locate package
    # linux-image-vendor-rk35xx" turned out to be for the Armbian repo.
    for base_tree in ["mkosi.sandbox", "mkosi.skeleton", "mkosi.extra"]:
        lines = user_repo_lines if base_tree == "mkosi.sandbox" else repo_lines
        sources_dir = os.path.join(workspace_path, base_tree, "etc", "apt", "sources.list.d")
        os.makedirs(sources_dir, exist_ok=True)
        custom_list = os.path.join(sources_dir, "custom.list")
        if lines:
            with open(custom_list, "w") as f:
                f.write("\n".join(lines) + "\n")
        elif os.path.exists(custom_list):
            # The workspace is reused between builds, so a file written by an
            # earlier run would otherwise survive into an image that must not
            # carry these sources any more.
            os.remove(custom_list)

    # 3. Assets overlay
    # asset_hook_cmds collects assets flagged "Register as Post-Install Hook";
    # they are appended to the postinst body further below. Before this the
    # is_postinst flag was stored and returned by the API but never read by the
    # build, so ticking the box in the UI silently did nothing.
    asset_hook_cmds = []
    for asset in assets:
        if os.path.exists(asset.file_path):
            if asset.install_target:
                target_rel = asset.install_target.lstrip("/")
                dest_file = os.path.join(extra_dir, target_rel)
            else:
                dest_file = os.path.join(extra_dir, "opt", "custom", asset.filename)

            os.makedirs(os.path.dirname(dest_file), exist_ok=True)
            shutil.copy2(asset.file_path, dest_file)

            if getattr(asset, "is_postinst", False):
                # Path as seen from inside the image (mkosi.extra is overlaid
                # onto /), not the workspace path.
                in_image = "/" + os.path.relpath(dest_file, extra_dir)
                q_path = shlex.quote(in_image)
                if in_image.endswith(".deb"):
                    asset_hook_cmds.append(
                        f"echo '[POSTINST] Installing asset package {os.path.basename(in_image)}'\n"
                        f"dpkg -i {q_path} 2>/dev/null || apt-get -y -f install || true"
                    )
                else:
                    asset_hook_cmds.append(
                        f"echo '[POSTINST] Running asset hook {os.path.basename(in_image)}'\n"
                        f"chmod +x {q_path} 2>/dev/null || true\n"
                        f"{q_path} || true"
                    )

    # 3.4. Release-Isolated Persistent APT Package Cache configuration
    rel_clean = (recipe.release if recipe and recipe.release else "default").lower().replace(" ", "_")
    release_apt_cache = os.path.join(os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace"), "cache", f"apt_{rel_clean}")
    os.makedirs(release_apt_cache, exist_ok=True)

    # Pre-seed rootfs APT cache directory from persistent host cache
    extra_apt_archives = os.path.join(workspace_path, "mkosi.extra", "var", "cache", "apt", "archives")
    os.makedirs(extra_apt_archives, exist_ok=True)
    if os.path.exists(release_apt_cache):
        for cached_file in os.listdir(release_apt_cache):
            if cached_file.endswith(".deb"):
                src_p = os.path.join(release_apt_cache, cached_file)
                dst_p = os.path.join(extra_apt_archives, cached_file)
                if not os.path.exists(dst_p):
                    try:
                        shutil.copy2(src_p, dst_p)
                    except Exception:
                        pass

    # 3.5. Prepare script — runs on HOST before package installation (mkosi v14)
    # Uses $BUILDROOT to access the rootfs. Writes custom repos and runs apt-get update
    # so that edge packages are resolvable when mkosi runs apt-get install.
    prepare_script_lines = [
        "#!/bin/bash",
        "set -e",
        'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH',
        '',
        '# Determine rootfs path — mkosi v14 passes $BUILDROOT',
        'ROOT="${BUILDROOT:-/}"',
        '',
        '# Write custom APT repos into the rootfs',
        'mkdir -p "$ROOT/etc/apt/sources.list.d"',
        "cat << 'REPOEOF' > \"$ROOT/etc/apt/sources.list.d/custom.list\"",
    ]
    prepare_script_lines.extend(repo_lines)
    prepare_script_lines.extend([
        "REPOEOF",
        '',
        '# Run apt-get update inside the rootfs chroot',
        '# Ensure host DNS resolv.conf is copied into rootfs so APT can resolve hosts',
        'cp -f /etc/resolv.conf "$ROOT/etc/resolv.conf" 2>/dev/null || true',
        'if [ "$ROOT" != "/" ] && [ -d "$ROOT/usr" ]; then',
        # /dev has to be re-bound RECURSIVELY. mkosi's own sandbox builds the
        # /dev it hands to build scripts as a tmpfs holding empty regular
        # files, with the real device nodes bind-mounted on top of them one by
        # one (see DevOperation in mkosi/sandbox.py). A plain "mount --bind"
        # copies only the tmpfs and drops every one of those submounts, so
        # $ROOT/dev/null ends up as the bare 0-byte root-owned regular file
        # underneath. apt-get update then runs apt-key as the unprivileged
        # _apt user, its "gpgv --version >/dev/null" probe dies with
        # "cannot create /dev/null: Permission denied", and apt concludes
        # "gpgv, gpgv2 or gpgv1 required for verification, but neither seems
        # installed" -- while gpgv is in fact installed. --rbind carries the
        # submounts along and $ROOT/dev/null is a real character device.
        '  mount -t proc proc "$ROOT/proc" || echo "[PREPARE] WARNING: proc mount failed ($?)"',
        '  mount -t sysfs sys "$ROOT/sys" || echo "[PREPARE] WARNING: sysfs mount failed ($?)"',
        '  mount --rbind /dev "$ROOT/dev" || echo "[PREPARE] WARNING: /dev bind mount failed ($?)"',
        '  [ -c "$ROOT/dev/null" ] || echo "[PREPARE] WARNING: $ROOT/dev/null is not a device node ($(ls -la "$ROOT/dev/null" 2>&1)) -- apt signature checks will fail"',
        '  chroot "$ROOT" apt-get update --allow-insecure-repositories || true',
        '  umount "$ROOT/proc" 2>/dev/null || true',
        '  umount "$ROOT/sys" 2>/dev/null || true',
        '  umount -R -l "$ROOT/dev" 2>/dev/null || true',
        'elif command -v apt-get >/dev/null 2>&1; then',
        '  apt-get update --allow-insecure-repositories || true',
        'fi',
    ])

    prepare_path = os.path.join(workspace_path, "mkosi.prepare")
    with open(prepare_path, "w") as f:
        f.write("\n".join(prepare_script_lines) + "\n")
    os.chmod(prepare_path, 0o755)

    # 4. Post-install script hook & timezone setup
    # NOTE: In mkosi v14 (Debian package), mkosi.postinst runs on the HOST with $BUILDROOT
    # pointing to the rootfs. We must chroot into $BUILDROOT to modify the target image.
    # Edge packages are installed by mkosi itself via [Content] Packages= after
    # mkosi.prepare.chroot adds custom APT repos.
    postinst_commands = []

    if recipe.timezone and recipe.timezone.strip():
        tz = recipe.timezone.strip()
        postinst_commands.append(f"ln -sf /usr/share/zoneinfo/{tz} /etc/localtime 2>/dev/null && echo \"{tz}\" > /etc/timezone 2>/dev/null || true")

    # System locale. C.UTF-8 is built into glibc and needs no generation; any
    # other locale has to be uncommented in /etc/locale.gen and compiled by
    # locale-gen (from the "locales" package) before update-locale can select
    # it. Note RemoveFiles strips /usr/share/locale/* (program translations),
    # not /usr/lib/locale (the compiled locale archive), so the locale itself
    # still works -- only translated program messages are absent.
    locale_val = (getattr(recipe, "locale", None) or "C.UTF-8").strip()
    if locale_val:
        q_locale = shlex.quote(locale_val)
        postinst_commands.append("\n".join([
            f"echo '[POSTINST] Configuring locale {locale_val}'",
            f"LOC={q_locale}",
            'if [ "$LOC" != "C.UTF-8" ] && [ "$LOC" != "C" ] && [ "$LOC" != "POSIX" ]; then',
            '  if [ -f /etc/locale.gen ]; then',
            '    grep -q "^$LOC " /etc/locale.gen 2>/dev/null || echo "$LOC UTF-8" >> /etc/locale.gen',
            '    sed -i "s/^# *\\($LOC \\)/\\1/" /etc/locale.gen 2>/dev/null || true',
            '  fi',
            '  command -v locale-gen >/dev/null 2>&1 && locale-gen "$LOC" 2>/dev/null || true',
            'fi',
            'if command -v update-locale >/dev/null 2>&1; then',
            '  update-locale LANG="$LOC" 2>/dev/null || true',
            'else',
            '  echo "LANG=$LOC" > /etc/default/locale',
            'fi',
        ]))

    # Credentials: root password and additional login accounts.
    # Without this the image ships root:* in /etc/shadow -- a locked account --
    # so password login is impossible on console, serial and SSH alike, leaving
    # only the console autologin and recipe ssh_keys as a way in.
    #
    # Passwords are piped to chpasswd inside the chroot, so the image stores
    # only the resulting crypt hash and never the plaintext. A value that
    # already looks like a crypt(3) hash ("$6$...") is installed verbatim with
    # "chpasswd -e" instead of being hashed a second time. Every interpolated
    # value is shell-quoted; usernames and group names are additionally
    # restricted to the POSIX portable set by the API schema.
    def _chpasswd_cmd(account: str, password: str) -> str:
        entry = shlex.quote(f"{account}:{password}")
        already_hashed = bool(re.match(r'^\$[0-9a-zA-Z]+\$', password))
        flag = " -e" if already_hashed else ""
        return f"echo {entry} | chpasswd{flag} || true"

    if recipe.root_password and recipe.root_password.strip():
        postinst_commands.append(
            "echo '[POSTINST] Setting root password'\n"
            + _chpasswd_cmd("root", recipe.root_password.strip())
        )

    if recipe.users and isinstance(recipe.users, list):
        for account in recipe.users:
            if not isinstance(account, dict):
                continue
            username = (account.get("username") or "").strip()
            if not username:
                continue
            shell_path = (account.get("shell") or "/bin/bash").strip()
            groups = [str(g).strip() for g in (account.get("groups") or []) if str(g).strip()]
            q_user = shlex.quote(username)

            lines = [f"echo '[POSTINST] Creating user {username}'"]
            lines.append(
                f"id -u {q_user} >/dev/null 2>&1 || "
                f"useradd -m -s {shlex.quote(shell_path)} {q_user} || true"
            )
            for group in groups:
                # -f makes this a no-op when the group already exists, and
                # creates it when it does not (netdev, for instance, is absent
                # from a minimal image even though the old preseed used it).
                lines.append(f"groupadd -f {shlex.quote(group)} 2>/dev/null || true")
            if groups:
                lines.append(f"usermod -aG {shlex.quote(','.join(groups))} {q_user} || true")
            password = account.get("password")
            if password:
                lines.append(_chpasswd_cmd(username, str(password)))

            # Ключи раньше доставались только root. Если вход root по паролю
            # закрыт (умолчание), а ходить предполагается под обычным
            # пользователем, без этого на плату было бы не попасть по ключу.
            # Домашний каталог берётся из passwd: useradd мог получить -m,
            # а мог и не создать его.
            if recipe.ssh_keys:
                q_keys = shlex.quote("\n".join(recipe.ssh_keys) + "\n")
                lines.append(f'_home="$(getent passwd {q_user} | cut -d: -f6)"')
                lines.append(
                    f'if [ -n "$_home" ]; then '
                    f'mkdir -p "$_home/.ssh" && '
                    f'printf %s {q_keys} > "$_home/.ssh/authorized_keys" && '
                    f'chmod 700 "$_home/.ssh" && chmod 600 "$_home/.ssh/authorized_keys" && '
                    f'chown -R {q_user}: "$_home/.ssh"; fi || true'
                )
            postinst_commands.append("\n".join(lines))

    hostname_mac_script = r"""
# Auto-configure hostname to equal active network interface MAC address (strictly lowercase, no colons/delimiters)
IFACE=$(ip -4 route show default 2>/dev/null | awk '/default/ {print $5}' | head -n 1)
if [ -z "$IFACE" ]; then
  IFACE=$(ip -o link show 2>/dev/null | awk -F': ' '$2 != "lo" {print $2; exit}')
fi
if [ -n "$IFACE" ]; then
  MAC=$(cat /sys/class/net/$IFACE/address 2>/dev/null | tr -d ':' | tr '[:upper:]' '[:lower:]')
  if [ -n "$MAC" ]; then
    echo "Setting hostname to MAC address: $MAC (interface: $IFACE)"
    hostnamectl set-hostname "$MAC" 2>/dev/null || echo "$MAC" > /etc/hostname
    # A minimal mkosi image ships no /etc/hosts at all (that convention comes
    # from debian-installer, not from the base packages), so "sed -i" on a
    # missing or 127.0.1.1-less file was a silent no-op: nothing ever pointed
    # the new hostname at localhost. Every "sudo" run afterwards then printed
    # "unable to resolve host <mac>" -- harmless, but on every single command.
    if [ ! -f /etc/hosts ]; then
      printf '127.0.0.1\tlocalhost\n127.0.1.1\t%s\n' "$MAC" > /etc/hosts
    elif grep -q '^127\.0\.1\.1' /etc/hosts 2>/dev/null; then
      sed -i "s/127.0.1.1.*/127.0.1.1\t$MAC/g" /etc/hosts 2>/dev/null || true
    else
      printf '127.0.1.1\t%s\n' "$MAC" >> /etc/hosts
    fi
  fi
fi
"""

    if recipe.hostname_from_netif:
        postinst_commands.append(hostname_mac_script)

    # Asset hooks run before the recipe's own raw postinst, so a custom script
    # can rely on anything the uploaded assets installed.
    postinst_commands.extend(asset_hook_cmds)

    if recipe.raw_postinst and recipe.raw_postinst.strip():
        postinst_commands.append(recipe.raw_postinst.strip())

    # Clean formatted postinst commands
    postinst_body = "\n".join(postinst_commands) if postinst_commands else "echo '[POSTINST] Complete.'"

    # Compose the systemd-boot loader entry cmdline from the recipe.
    # This entry is what actually boots (loader.conf sets "default edge.conf"),
    # so hardcoding the options here meant recipe.kernel_params only ever
    # reached mkosi's UKI and had no effect on a normal boot. Defaults are only
    # added when the recipe has not already specified an equivalent, so a recipe
    # can override the console or verbosity without ending up with duplicates.
    _kp = (recipe.kernel_params or "").strip()
    # Only the armbian flow needs the PARTUUID: it is the one that clones the
    # boot medium onto another disk, leaving two filesystems answering to
    # LABEL=edgeroot at once (see IMAGE_ROOT_PARTUUID). The amd64 images have
    # no such duality, so their loader entry is left alone.
    _root_spec = (
        f"root=PARTUUID={IMAGE_ROOT_PARTUUID}"
        if is_armbian(recipe.distribution)
        else "root=LABEL=edgeroot"
    )
    _loader_opts = [_root_spec, "rw"]
    if "quiet" not in _kp:
        _loader_opts += ["quiet", "loglevel=3"]
    if "fsck.mode" not in _kp:
        _loader_opts.append("fsck.mode=skip")
    if "console=" not in _kp:
        _loader_opts += ["console=tty0", f"console={board_console(getattr(recipe, 'board', None))}"]
    if _kp:
        _loader_opts.append(_kp)
    loader_options = " ".join(_loader_opts)

    # U-Boot на RK3588 не понимает записи systemd-boot: он ищет boot.scr или
    # extlinux/extlinux.conf. Без этого файла загрузчик стартует, но грузить
    # ему нечего -- образ выглядит собранным и молча не поднимается на плате.
    # FDT обязателен: без device tree ядро RK3588 не найдёт ни память, ни
    # периферию. Если DTB платы почему-то не приехал, FDTDIR даёт U-Boot
    # выбрать его самому по своему fdtfile -- лучше, чем ссылка в никуда.
    extlinux_block = ""
    if is_armbian(recipe.distribution):
        dtb_rel = board_dtb(getattr(recipe, "board", None))
        extlinux_block = f"""
    mkdir -p /boot/extlinux
    {{
      echo "LABEL Edge OS"
      echo "  LINUX $KIMG"
      echo "  INITRD $IIMG"
      if [ -n "{dtb_rel}" ] && [ -f "/boot/dtb-$KVER/{dtb_rel}" ]; then
        echo "  FDT /dtb-$KVER/{dtb_rel}"
      else
        echo "  FDTDIR /dtb-$KVER/"
      fi
      echo "  APPEND {loader_options}"
    }} > /boot/extlinux/extlinux.conf
    echo "[POSTINST] extlinux.conf for U-Boot:"
    cat /boot/extlinux/extlinux.conf
"""

    # virtio -- guest disks/network under QEMU/VirtualBox, isofs/sr_mod/cdrom --
    # booting from an ISO installer. RK3588 is bare metal with no ISO mode at
    # all (see extlinux_block above), so for Armbian this is pure dead weight:
    # a second initramfs generation (~27s) for modules that will never be
    # needed.
    virtio_iso_modules_block = ""
    if not is_armbian(recipe.distribution):
        virtio_iso_modules_block = """
    # Ensure initramfs is generated with all required modules for VirtualBox/virtio
    # AND ISO installer boot (isofs/sr_mod/cdrom for CD-ROM boot media mounting)
    if [ -n "$KVER" ] && command -v update-initramfs >/dev/null 2>&1; then
      echo "[POSTINST] Adding virtio + ISO boot modules to initramfs-tools/modules..."
      for m in virtio_blk virtio_pci virtio_net virtio_scsi virtio_console \\
               vfat fat ext4 ahci sd_mod scsi_mod \\
               isofs sr_mod cdrom loop usbcore usb-storage; do
        grep -qxF "$m" /etc/initramfs-tools/modules 2>/dev/null || echo "$m" >> /etc/initramfs-tools/modules
      done
      echo "[POSTINST] Regenerating initramfs for kernel $KVER with virtio+ISO modules..."
      update-initramfs -u -k "$KVER" || true
    fi
"""

    postinst_script = f"""#!/bin/bash
set -e
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

ROOT="${{BUILDROOT:-/}}"

# Copy host DNS configuration into rootfs for chroot network access
cp -f /etc/resolv.conf "$ROOT/etc/resolv.conf" 2>/dev/null || true

# 1. Install pre-downloaded Edge platform .deb packages inside chroot
if [ -d "$ROOT/opt/edge_packages" ] && [ -n "$(ls -A "$ROOT/opt/edge_packages"/*.deb 2>/dev/null)" ]; then
  echo "[POSTINST] Installing pre-downloaded Edge platform packages via dpkg..."
  # Mount pseudo-filesystems for apt/dpkg to work correctly. /dev must be
  # bound recursively -- see the comment on the prepare script's own mounts:
  # a plain --bind loses mkosi's per-node submounts and leaves /dev/null as an
  # unwritable regular file, which silently breaks apt signature verification.
  mount -t proc proc "$ROOT/proc" 2>/dev/null || true
  mount -t sysfs sys "$ROOT/sys" 2>/dev/null || true
  mount --rbind /dev "$ROOT/dev" 2>/dev/null || true

  chroot "$ROOT" /bin/bash -c "
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:\\$PATH
    ln -sf /bin/bash /bin/sh
    mkdir -p /opt/edge/venv/bin /opt/edge/bin /usr/bin
    if [ ! -f /opt/edge/venv/bin/python3.14 ]; then
      ln -sf /usr/bin/python3 /opt/edge/venv/bin/python3.14 2>/dev/null || true
      ln -sf /usr/bin/python3 /opt/edge/venv/bin/python3 2>/dev/null || true
      ln -sf /usr/bin/python3 /opt/edge/venv/bin/python 2>/dev/null || true
    fi

    if ! command -v apt-mark >/dev/null 2>&1; then
      echo '#!/bin/bash' > /usr/bin/apt-mark
      echo 'exit 0' >> /usr/bin/apt-mark
      chmod +x /usr/bin/apt-mark
    fi

    if [ ! -f /opt/edge/bin/ctrl-cli ] || [ ! -x /opt/edge/bin/ctrl-cli ]; then
      echo '#!/bin/bash' > /opt/edge/bin/ctrl-cli
      echo 'exit 0' >> /opt/edge/bin/ctrl-cli
      chmod +x /opt/edge/bin/ctrl-cli
    fi

    # 1. Unpack all deb packages without running postinst scripts
    dpkg --unpack --force-depends --force-overwrite /opt/edge_packages/*.deb || true

    # 2. Pre-create directories and files expected by edge-base postinst
    mkdir -p /etc/edge/webserver.0 /etc/edge /opt/edge/bin /opt/edge/venv/bin
    touch /etc/edge/webserver.0/htpasswd 2>/dev/null || true

    # 3. Fix bash double bracket syntax in autosdk script if present
    if [ -f /opt/edge/share/etc/environment.d/02-autosdk.sh ]; then
      sed -i 's/\\[\\[/\\[/g; s/\\]\\]/\\]/g' /opt/edge/share/etc/environment.d/02-autosdk.sh 2>/dev/null || true
    fi

    # 4. Convert strict 'set -e' to non-blocking 'set +e' in all postinst scripts for chroot build safety
    for pscript in /var/lib/dpkg/info/*.postinst /var/lib/dpkg/info/*.preinst; do
      if [ -f \"\\$pscript\" ]; then
        sed -i 's/^set -e/set +e/g' \"\\$pscript\" 2>/dev/null || true
        sed -i 's|/opt/edge/bin/ctrl-cli|/bin/true|g' \"\\$pscript\" 2>/dev/null || true
      fi
    done

    # 5. Overwrite ctrl-cli executable with a clean stub if it fails at runtime in chroot
    echo '#!/bin/bash' > /opt/edge/bin/ctrl-cli
    echo 'exit 0' >> /opt/edge/bin/ctrl-cli
    chmod +x /opt/edge/bin/ctrl-cli

    # 6. Fetch missing dependencies and configure all unpacked packages
    export DEBIAN_FRONTEND=noninteractive
    rm -f /etc/apt/apt.conf.d/*mkosi* /etc/apt/apt.conf.d/*cache* 2>/dev/null || true
    mkdir -p /var/cache/apt/archives/partial /var/lib/apt/lists/partial
    apt-get update --allow-insecure-repositories || true
    apt-get install -f -y --allow-unauthenticated || true
    dpkg --configure --pending --force-depends || true
  "

  # Unmount pseudo-filesystems
  umount "$ROOT/proc" 2>/dev/null || true
  umount "$ROOT/sys" 2>/dev/null || true
  umount -R -l "$ROOT/dev" 2>/dev/null || true

  rm -rf "$ROOT/opt/edge_packages"
fi

# 2. Run recipe post-install hooks (timezone, hostname MAC, custom scripts)
if [ "$ROOT" != "/" ] && [ -d "$ROOT/tmp" ]; then
  cat << 'HOOKEOF' > "$ROOT/tmp/recipe_postinst.sh"
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
{postinst_body}
HOOKEOF
  chmod +x "$ROOT/tmp/recipe_postinst.sh"
  chroot "$ROOT" /bin/bash /tmp/recipe_postinst.sh || true
  rm -f "$ROOT/tmp/recipe_postinst.sh"
else
  {postinst_body}
fi
# 3. Clean up non-Intel firmware, docs, locales, machine-id for ConditionFirstBoot, and APT caches from rootfs
echo "[POSTINST] Stripping non-Intel firmware, documentation, and uninitializing machine-id for firstboot..."
rm -f "$ROOT"/etc/machine-id || true
rm -rf "$ROOT"/usr/lib/firmware/nvidia* "$ROOT"/usr/lib/firmware/amdgpu* "$ROOT"/usr/lib/firmware/radeon* "$ROOT"/usr/lib/firmware/qcom* "$ROOT"/usr/lib/firmware/mellanox* "$ROOT"/usr/lib/firmware/mrvl* "$ROOT"/usr/lib/firmware/mediatek* "$ROOT"/usr/lib/firmware/broadcom* "$ROOT"/usr/lib/firmware/brcm* "$ROOT"/usr/lib/firmware/ath9k* "$ROOT"/usr/lib/firmware/ath10k* "$ROOT"/usr/lib/firmware/ath11k* "$ROOT"/usr/lib/firmware/ath12k* "$ROOT"/usr/lib/firmware/cxgb3* "$ROOT"/usr/lib/firmware/cxgb4* "$ROOT"/usr/lib/firmware/liquidio* "$ROOT"/usr/lib/firmware/netronome* "$ROOT"/usr/share/doc/* "$ROOT"/usr/share/man/* "$ROOT"/usr/share/info/* "$ROOT"/usr/share/help/* "$ROOT"/usr/share/gtk-doc/* "$ROOT"/usr/share/locale/* "$ROOT"/usr/share/sounds/* "$ROOT"/usr/share/icons/* || true

# 4. Ensure systemd-boot bootloader, vmlinuz, and initrd are prepared in /boot (ESP partition)
echo "[POSTINST] Initializing systemd-boot and copying kernel/initrd into /boot..."
if [ "$ROOT" != "/" ] && [ -d "$ROOT/tmp" ]; then
  # Re-mount pseudo-filesystems for bootctl and update-initramfs to work correctly
  mount -t proc proc "$ROOT/proc" 2>/dev/null || true
  mount -t sysfs sys "$ROOT/sys" 2>/dev/null || true
  mount --rbind /dev "$ROOT/dev" 2>/dev/null || true
  mount -t devpts devpts "$ROOT/dev/pts" 2>/dev/null || true

  chroot "$ROOT" /bin/bash -c '
    export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH
    # Install the bootloader into /boot, not the bootctl default of /efi. The
    # ESP repart definition copies /boot into the ESP root (CopyFiles=/boot:/),
    # so anything bootctl writes to /efi never reaches the ESP -- which left the
    # installed disk with no /EFI/BOOT/BOOTX64.EFI and made UEFI firmware report
    # "No bootable option or device was found" once the install ISO was removed.
    bootctl install --esp-path=/boot --no-variables 2>/dev/null || true

    # bootctl may refuse a non-FAT --esp-path, so place the EFI binaries
    # directly as well. Both destinations are what UEFI firmware looks for:
    # EFI/BOOT/BOOT<arch>.EFI is the removable-media fallback path.
    mkdir -p /boot/EFI/BOOT /boot/EFI/systemd
    for sb in /usr/lib/systemd/boot/efi/systemd-boot*.efi; do
      [ -f "$sb" ] || continue
      cp -f "$sb" /boot/EFI/systemd/ 2>/dev/null || true
      sb_arch=$(basename "$sb" .efi | sed s/^systemd-boot//)
      sb_upper=$(echo "$sb_arch" | tr "[:lower:]" "[:upper:]")
      cp -f "$sb" "/boot/EFI/BOOT/BOOT$sb_upper.EFI" 2>/dev/null || true
      echo "[POSTINST] Installed $sb as /boot/EFI/BOOT/BOOT$sb_upper.EFI"
    done

    KVER=$(ls /lib/modules 2>/dev/null | sort -V | tail -n1)

    # Запрет из mkosi.skeleton снимается безусловно, до всех проверок: если он
    # уедет в готовый образ, плата перестанет пересобирать initramfs при
    # обновлении ядра и однажды загрузится со старым.
    rm -f /etc/initramfs-tools/update-initramfs.conf

    {virtio_iso_modules_block}
    for f in /boot/vmlinuz-$KVER /boot/vmlinuz* /vmlinuz*; do
      if [ -f "$f" ] && [ "$f" != "/boot/vmlinuz" ]; then
        cp -f "$f" /boot/vmlinuz 2>/dev/null || true
        break
      fi
    done
    for f in /boot/initrd.img-$KVER /boot/initrd* /boot/initramfs* /initrd* /initramfs*; do
      if [ -f "$f" ] && [ "$f" != "/boot/initrd.img" ]; then
        cp -f "$f" /boot/initrd.img 2>/dev/null || true
        break
      fi
    done
    # Point the loader entry at kernel/initrd paths that actually exist in the
    # ESP. The plain /boot/vmlinuz copy above is not always produced, and an
    # entry referencing a missing file makes systemd-boot fail on its default
    # entry, so prefer the versioned names and fall back to the plain ones.
    KIMG=""
    IIMG=""
    if [ -f "/boot/vmlinuz-$KVER" ]; then
      KIMG="/vmlinuz-$KVER"
    elif [ -f /boot/vmlinuz ]; then
      KIMG="/vmlinuz"
    fi
    if [ -f "/boot/initrd.img-$KVER" ]; then
      IIMG="/initrd.img-$KVER"
    elif [ -f /boot/initrd.img ]; then
      IIMG="/initrd.img"
    fi

    mkdir -p /boot/loader/entries
    echo "timeout 3" > /boot/loader/loader.conf
    echo "console-mode max" >> /boot/loader/loader.conf
    if [ -n "$KIMG" ] && [ -n "$IIMG" ]; then
      echo "default edge.conf" >> /boot/loader/loader.conf
      echo "title Edge OS" > /boot/loader/entries/edge.conf
      echo "linux $KIMG" >> /boot/loader/entries/edge.conf
      echo "initrd $IIMG" >> /boot/loader/entries/edge.conf
      echo "options {loader_options}" >> /boot/loader/entries/edge.conf
      echo "[POSTINST] Loader entry edge.conf -> linux $KIMG, initrd $IIMG"
    else
      # No loose kernel/initrd: drop the entry and let systemd-boot
      # auto-discover the UKI that mkosi generated in EFI/Linux.
      rm -f /boot/loader/entries/edge.conf
      echo "[POSTINST] WARNING: no kernel/initrd in /boot (KVER=$KVER); relying on UKI in EFI/Linux"
    fi

{extlinux_block}
    echo "[POSTINST] ESP staging /boot contents:"
    ls -la /boot 2>/dev/null || true
    echo "[POSTINST] ESP staging /boot/EFI/BOOT contents:"
    ls -la /boot/EFI/BOOT 2>/dev/null || true

    # mkosi'"'"'s Autologin=yes writes getty overrides ending in a bare "$TERM"
    # token (see getty@tty1.service.d and console-getty.service.d). That is
    # only meaningful under systemd-nspawn, which imports TERM from the host;
    # on a real boot (this disk image booted as a VM/bare metal) nothing ever
    # sets TERM in PID 1'"'"'s environment, so agetty inherits an undefined
    # terminal type. Force a known-good "linux" TERM so autologin does not
    # depend on that substitution succeeding.
    for gdrop in /etc/systemd/system/getty@tty1.service.d/*.conf \
                 /etc/systemd/system/console-getty.service.d/*.conf; do
      [ -f "$gdrop" ] || continue
      sed -i "s/ \\$TERM/ linux/" "$gdrop"
      grep -q "^Environment=TERM=" "$gdrop" || sed -i "/^\\[Service\\]/a Environment=TERM=linux" "$gdrop"
      echo "[POSTINST] Pinned TERM=linux in $gdrop"
    done
  ' || true

  # Unmount pseudo-filesystems
  umount "$ROOT/dev/pts" 2>/dev/null || true
  umount "$ROOT/proc" 2>/dev/null || true
  umount "$ROOT/sys" 2>/dev/null || true
  umount -R -l "$ROOT/dev" 2>/dev/null || true
fi

# The very first thing this script did was overwrite /etc/resolv.conf with
# the build host's own copy (Docker's 127.0.0.11 in this setup) so the chroot
# steps above could resolve apt mirrors. That value is meaningless once this
# image boots on real hardware -- restore the static fallback now that every
# network-needing step is done.
cat << 'RESOLVEOF' > "$ROOT/etc/resolv.conf"
{FALLBACK_RESOLV_CONF}RESOLVEOF
"""
    # mkosi.postinst and mkosi.finalize are two separate hooks that both always
    # run when both files are present -- writing the same script to both meant
    # every postinst step (package install, extlinux.conf, firmware pruning)
    # ran twice per build.
    postinst_path = os.path.join(workspace_path, "mkosi.postinst")
    with open(postinst_path, "w") as f:
        f.write(postinst_script)
    os.chmod(postinst_path, 0o755)

    # 5. Firstboot script & systemd service
    firstboot_lines = ["#!/bin/bash", "set -e"]

    if recipe.hostname_from_netif:
        firstboot_lines.append(hostname_mac_script)

    # Переименование идёт до всего остального: дальше по скрипту интерфейсы уже
    # должны называться так, как записано в рецепте.
    net_prefix = (recipe.network_config or {}).get("prefix") if isinstance(recipe.network_config, dict) else None
    if net_prefix:
        start_index = (recipe.network_config or {}).get("start_index", DEFAULT_START_INDEX)
        try:
            start_index = int(start_index)
        except (TypeError, ValueError):
            start_index = DEFAULT_START_INDEX

        # Отдельным файлом, а не вставкой в firstboot.sh: плату могут включить
        # без единого воткнутого кабеля, и тогда переименование откладывается
        # до первого линка. Доиграть его по горячему подключению можно только
        # тем, что запускается повторно, а firstboot -- oneshot с
        # RemainAfterExit и второй раз уже не стартует.
        netnames_bin_dir = os.path.join(extra_dir, "opt", "edge", "bin")
        os.makedirs(netnames_bin_dir, exist_ok=True)
        netnames_path = os.path.join(netnames_bin_dir, "netnames.sh")
        with open(netnames_path, "w") as f:
            f.write("#!/bin/bash\n" + rename_script(str(net_prefix), start_index))
        os.chmod(netnames_path, 0o755)
        firstboot_lines.append("/opt/edge/bin/netnames.sh")

        netnames_systemd_dir = os.path.join(extra_dir, "etc", "systemd", "system")
        os.makedirs(netnames_systemd_dir, exist_ok=True)
        with open(os.path.join(netnames_systemd_dir, "edge-netnames.service"), "w") as f:
            f.write(f"""[Unit]
Description=Edge OS Interface Naming
ConditionPathExists=!{NETNAMES_STAMP}

[Service]
Type=oneshot
ExecStart=/opt/edge/bin/netnames.sh
StandardOutput=journal+console
StandardError=journal+console
""")

        udev_dir = os.path.join(extra_dir, "etc", "udev", "rules.d")
        os.makedirs(udev_dir, exist_ok=True)
        with open(os.path.join(udev_dir, "80-edge-netnames.rules"), "w") as f:
            f.write(
                "# Naming is deferred while no port has a link: the first name must land on\n"
                "# the port the board actually works through. Finish it when a cable appears,\n"
                "# instead of waiting for the next reboot.\n"
                'ACTION=="change", SUBSYSTEM=="net", ATTR{carrier}=="1", '
                'TAG+="systemd", ENV{SYSTEMD_WANTS}+="edge-netnames.service"\n'
            )

    if recipe.raw_firstboot and recipe.raw_firstboot.strip():
        firstboot_lines.append(recipe.raw_firstboot.strip())

    # Клонирование на NVMe идёт последним: до него скрипт успевает задать
    # hostname и всё, что рецепт дописал сам, и на диск уезжает уже
    # настроенная система.
    if is_armbian(recipe.distribution):
        firstboot_lines.append(provision_script())

    if len(firstboot_lines) > 2:
        fb_bin_dir = os.path.join(extra_dir, "opt", "edge", "bin")
        os.makedirs(fb_bin_dir, exist_ok=True)
        fb_script_path = os.path.join(fb_bin_dir, "firstboot.sh")
        with open(fb_script_path, "w") as f:
            f.write("\n".join(firstboot_lines) + "\n")
        os.chmod(fb_script_path, 0o755)

        systemd_dir = os.path.join(extra_dir, "etc", "systemd", "system")
        os.makedirs(systemd_dir, exist_ok=True)
        fb_svc_path = os.path.join(systemd_dir, "edge-firstboot.service")
        with open(fb_svc_path, "w") as f:
            f.write("""[Unit]
Description=Edge Firstboot Initialization Service
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/opt/edge/bin/firstboot.sh
RemainAfterExit=yes
# Клонирование на NVMe -- это посекторная копия всего образа, и на медленной
# карте она идёт минутами. Со штатным DefaultTimeoutStartSec (90 с) systemd
# убивал firstboot прямо посреди dd: на цель успевала уехать таблица разделов
# и первые разделы, а корень оставался пустым -- ядро потом не находило
# LABEL=edgeroot и падало в initramfs. Прошивка SPI идёт после dd и тоже не
# успевала. Предел оставлен конечным, чтобы зависший носитель не держал
# загрузку вечно.
TimeoutStartSec=30min

[Install]
WantedBy=multi-user.target
""")

        wants_dir = os.path.join(extra_dir, "etc", "systemd", "system", "multi-user.target.wants")
        os.makedirs(wants_dir, exist_ok=True)
        link_path = os.path.join(wants_dir, "edge-firstboot.service")
        if not os.path.exists(link_path):
            try:
                os.symlink("/etc/systemd/system/edge-firstboot.service", link_path)
            except Exception:
                pass


    # 5b. Disk expansion service (always installed, independent of the optional
    # firstboot script above). The installer deploys images with a byte-for-byte
    # dd, so the backup GPT header and last-usable-LBA still describe the smaller
    # source image rather than the target disk. Until those are corrected the
    # trailing partition cannot claim the extra capacity, stranding most of a
    # large disk (a 9.5 GiB image on a 25 GiB disk leaves ~15 GiB unusable).
    growfs_bin_dir = os.path.join(extra_dir, "opt", "edge", "bin")
    os.makedirs(growfs_bin_dir, exist_ok=True)
    growfs_script_path = os.path.join(growfs_bin_dir, "growfs.sh")
    with open(growfs_script_path, "w") as f:
        f.write("""#!/bin/sh
# Expand the last GPT partition of the boot disk to fill the physical device.
# Runs once, then drops a stamp file so subsequent boots are no-ops.
# Only uses util-linux + e2fsprogs tooling, both present in a base install.
STAMP=/var/lib/edge/growfs.done
[ -e "$STAMP" ] && exit 0

log() { echo "[GROWFS] $*"; }

ROOT_SRC=$(findmnt -n -o SOURCE / 2>/dev/null)
ROOT_DEV=$(readlink -f "$ROOT_SRC" 2>/dev/null)
case "$ROOT_DEV" in
    /dev/*) ;;
    *) log "cannot resolve root device from '$ROOT_SRC', skipping"; exit 0 ;;
esac

PK=$(lsblk -no PKNAME "$ROOT_DEV" 2>/dev/null | head -n1 | tr -d ' ')
[ -n "$PK" ] || { log "root $ROOT_DEV is not on a partitioned disk, skipping"; exit 0; }
DISK="/dev/$PK"
[ -b "$DISK" ] || { log "$DISK is not a block device, skipping"; exit 0; }

LAST_PART=$(lsblk -nrpo NAME,TYPE "$DISK" 2>/dev/null | awk '$2=="part" {p=$1} END {print p}')
[ -n "$LAST_PART" ] || { log "no partitions found on $DISK, skipping"; exit 0; }
LAST_NR=$(echo "$LAST_PART" | grep -o '[0-9]*$')
[ -n "$LAST_NR" ] || { log "cannot parse partition number from $LAST_PART, skipping"; exit 0; }

# Move the backup GPT header and last-usable-LBA to the true end of the disk.
log "relocating backup GPT header on $DISK"
if ! sfdisk --relocate gpt-bak-std "$DISK" >/dev/null 2>&1; then
    log "GPT relocation reported an error (continuing)"
fi

# Extend the trailing partition over the space that just became addressable.
log "growing partition $LAST_NR of $DISK"
if ! echo ", +" | sfdisk -N "$LAST_NR" --no-reread --force "$DISK" >/dev/null 2>&1; then
    log "partition grow failed, leaving disk untouched"
    exit 0
fi

partx -u "$DISK" >/dev/null 2>&1 || partprobe "$DISK" >/dev/null 2>&1 || true
udevadm settle >/dev/null 2>&1 || true

FSTYPE=$(blkid -o value -s TYPE "$LAST_PART" 2>/dev/null)
case "$FSTYPE" in
    ext2|ext3|ext4)
        log "resizing $FSTYPE on $LAST_PART"
        resize2fs "$LAST_PART" || { log "resize2fs failed, will retry next boot"; exit 0; }
        ;;
    xfs)
        MP=$(findmnt -n -o TARGET "$LAST_PART" 2>/dev/null | head -n1)
        [ -n "$MP" ] || { log "xfs on $LAST_PART not mounted, cannot grow"; exit 0; }
        log "growing xfs mounted at $MP"
        xfs_growfs "$MP" || { log "xfs_growfs failed, will retry next boot"; exit 0; }
        ;;
    *)
        log "unsupported filesystem '$FSTYPE' on $LAST_PART, grew partition only"
        ;;
esac

mkdir -p /var/lib/edge
: > "$STAMP"
log "completed"
""")
    os.chmod(growfs_script_path, 0o755)

    growfs_systemd_dir = os.path.join(extra_dir, "etc", "systemd", "system")
    os.makedirs(growfs_systemd_dir, exist_ok=True)

    growfs_wants_dir = os.path.join(extra_dir, "etc", "systemd", "system", "multi-user.target.wants")
    os.makedirs(growfs_wants_dir, exist_ok=True)

    # On RK3588 there is nothing to grow at boot and no reason to: the card is a
    # transit medium (a grown card would mean every next board gets a copy the
    # size of the whole card), and the clone is grown by provisioning itself --
    # offline, on a target that is not mounted yet, right after the dd (see
    # core/rk3588.py). A unit here would redo exactly that work a second time and
    # on a mounted filesystem, so armbian ships it not at all.
    #
    # It used to be installed with ConditionPathExists on the provisioning
    # marker -- and silently never fired, because the marker was written into a
    # mount-point directory and was invisible on the running system (see
    # MARKER_PATH in rk3588.py). The duplication survived precisely because the
    # broken gate kept it out of sight.
    if not is_armbian(recipe.distribution):
        with open(os.path.join(growfs_systemd_dir, "edge-growfs.service"), "w") as f:
            f.write("""[Unit]
Description=Edge OS Expand Last Partition To Fill Disk
Documentation=man:sfdisk(8)
After=local-fs.target
Before=edge-firstboot.service
ConditionPathExists=!/var/lib/edge/growfs.done

[Service]
Type=oneshot
ExecStart=/opt/edge/bin/growfs.sh
RemainAfterExit=yes
StandardOutput=journal+console
StandardError=journal+console

[Install]
WantedBy=multi-user.target
""")

        growfs_link = os.path.join(growfs_wants_dir, "edge-growfs.service")
        if not os.path.exists(growfs_link):
            try:
                os.symlink("/etc/systemd/system/edge-growfs.service", growfs_link)
            except Exception:
                pass
    else:
        # Skipping the write above is not enough: mkosi.extra is never wiped
        # between builds, so a unit left by an earlier run of this same
        # workspace keeps shipping -- and it did. Caught on hardware: an
        # armbian image carried edge-growfs.service (dated two builds back)
        # plus its enabling symlink, growfs.sh ran against the boot disk, and
        # since the board boots off the card that disk WAS the card.
        # "sfdisk --relocate gpt-bak-std" then rewrote the card's GPT header
        # to point at the end of the physical card, and the partition entry
        # array no longer matched its own checksum. U-Boot tolerates that and
        # falls back to the backup table; Linux discards the table outright,
        # so the card came up with no partitions at all and the board silently
        # booted the installed system instead of the card under test.
        for stale in (
            os.path.join(growfs_systemd_dir, "edge-growfs.service"),
            os.path.join(growfs_wants_dir, "edge-growfs.service"),
            growfs_script_path,
        ):
            if os.path.exists(stale) or os.path.islink(stale):
                try:
                    os.remove(stale)
                except OSError:
                    pass

    # 5c. Edge network firstboot (systemd-networkd port of networking-cli).
    # The Edge platform's own /opt/edge/bin/networking-cli is built entirely on
    # ifupdown -- it calls "ifup" and "systemctl restart networking" and writes
    # /etc/network/interfaces.d/. ifupdown is not installed in mkosi images and
    # would fight systemd-networkd, so this reproduces the same result natively.
    #
    # Behaviour mirrored from edge.support.networking:
    #   primary NIC  = first interface with a live link (operstate/carrier),
    #                  DHCP plus the static alias 192.168.222.<last MAC octet>
    #   camera NICs  = remaining interfaces sorted, 192.168.<index+2>4.1/24
    #                  with MTU 6000 (jumbo frames)
    #   /etc/network/management-mac = primary MAC, required by the Edge web UI
    #                  (webserver/sysconf/api_network.py), the elevator hook
    #                  elevator.d/*/01-network and setup-cam-networks.py.
    netconf_script_path = os.path.join(growfs_bin_dir, "edge-netconf.sh")
    with open(netconf_script_path, "w") as f:
        f.write("""#!/bin/sh
# Configure networking the way the Edge platform expects, on systemd-networkd.
# Runs once, then stamps itself so later boots are no-ops.
STAMP=/var/lib/edge/netconf.done
[ -e "$STAMP" ] && exit 0

# Only meaningful on Edge images; a plain base image keeps the build-time
# DHCP catch-all and needs none of the camera/management-mac handling.
[ -d /opt/edge ] || exit 0

log() { echo "[EDGE-NET] $*"; }

NETDIR=/etc/systemd/network
mkdir -p "$NETDIR" /var/lib/edge /etc/network

# Physical NICs only: a real device has a /sys/class/net/<if>/device symlink,
# which excludes lo, bridges, veth and other virtual interfaces.
IFACES=""
for d in /sys/class/net/*; do
    n=$(basename "$d")
    [ "$n" = "lo" ] && continue
    [ -e "$d/device" ] || continue
    IFACES="$IFACES $n"
done
IFACES=$(echo $IFACES | tr ' ' '\\n' | sort | tr '\\n' ' ')
if [ -z "$IFACES" ]; then
    log "no physical interfaces found, leaving build-time defaults in place"
    exit 0
fi
log "physical interfaces:$IFACES"

# Links must be up before carrier can be read.
for n in $IFACES; do
    ip link set "$n" up 2>/dev/null || true
done

# Primary = first interface with a live link, same criterion networking-cli
# used (it polled for operstate UP / LOWER_UP for up to 60 seconds).
PRIMARY=""
attempt=0
while [ "$attempt" -lt 60 ]; do
    for n in $IFACES; do
        if [ "$(cat /sys/class/net/$n/carrier 2>/dev/null || echo 0)" = "1" ]; then
            PRIMARY="$n"
            break
        fi
    done
    [ -n "$PRIMARY" ] && break
    attempt=$((attempt + 1))
    sleep 1
done

if [ -z "$PRIMARY" ]; then
    PRIMARY=$(echo $IFACES | cut -d' ' -f1)
    log "no link detected after 60s, defaulting primary to $PRIMARY"
fi
log "primary interface: $PRIMARY"

MAC=$(cat "/sys/class/net/$PRIMARY/address" 2>/dev/null)
if [ -n "$MAC" ]; then
    echo "$MAC" > /etc/network/management-mac
    log "management-mac: $MAC"
fi

BYTE4=$(printf "%d" "0x$(echo "$MAC" | awk -F: '{print $6}')" 2>/dev/null || echo 1)
[ -n "$BYTE4" ] || BYTE4=1

# Match on the MAC rather than on the name: edge_apply_live_names (netnames.sh)
# changes the interface name after this file has been written, so
# Name=enP4p65s0 would stop matching and the interface would be left without an
# address entirely. The MAC never changes.
if [ -n "$MAC" ]; then
    PRIMARY_MATCH="MACAddress=$MAC"
else
    PRIMARY_MATCH="Name=$PRIMARY"
fi

cat > "$NETDIR/20-edge-primary-$PRIMARY.network" <<PRIMEOF
# Generated by D.U.R.O. edge-netconf
[Match]
$PRIMARY_MATCH

[Network]
DHCP=yes
Address=192.168.222.$BYTE4/24
PRIMEOF
log "primary $PRIMARY ($PRIMARY_MATCH): DHCP + 192.168.222.$BYTE4/24"

idx=0
for n in $IFACES; do
    [ "$n" = "$PRIMARY" ] && continue
    oct=$((idx + 2))
    CAM_MAC=$(cat "/sys/class/net/$n/address" 2>/dev/null)
    if [ -n "$CAM_MAC" ]; then
        CAM_MATCH="MACAddress=$CAM_MAC"
    else
        CAM_MATCH="Name=$n"
    fi
    cat > "$NETDIR/30-edge-cam$idx-$n.network" <<CAMEOF
# Generated by D.U.R.O. edge-netconf
[Match]
$CAM_MATCH

[Network]
Address=192.168.${oct}4.1/24

[Link]
MTUBytes=6000
CAMEOF
    log "camera $n ($CAM_MATCH): 192.168.${oct}4.1/24 mtu 6000"
    idx=$((idx + 1))
done

systemctl restart systemd-networkd 2>/dev/null || true
: > "$STAMP"
log "completed"
""")
    os.chmod(netconf_script_path, 0o755)

    with open(os.path.join(growfs_systemd_dir, "edge-netconf.service"), "w") as f:
        f.write("""[Unit]
Description=Edge OS Network Configuration (systemd-networkd)
After=local-fs.target systemd-networkd.service
Before=network-online.target edge-firstboot.service
ConditionPathExists=!/var/lib/edge/netconf.done

[Service]
Type=oneshot
ExecStart=/opt/edge/bin/edge-netconf.sh
RemainAfterExit=yes
StandardOutput=journal+console
StandardError=journal+console

[Install]
WantedBy=multi-user.target
""")

    netconf_link = os.path.join(growfs_wants_dir, "edge-netconf.service")
    if not os.path.exists(netconf_link):
        try:
            os.symlink("/etc/systemd/system/edge-netconf.service", netconf_link)
        except Exception:
            pass

    # 6. Debian Preseed file
    if recipe.raw_preseed_cfg and recipe.raw_preseed_cfg.strip():
        preseed_path = os.path.join(workspace_path, "preseed.cfg")
        with open(preseed_path, "w") as f:
            f.write(recipe.raw_preseed_cfg.strip() + "\n")


def cleanup_workspace(recipe_id: int):
    """
    Removes workspace directory for a deleted recipe.
    """
    base_dir = os.getenv("DURO_WORKSPACE_PATH", "/opt/data/duro_workspace")
    recipe_ws = os.path.join(base_dir, str(recipe_id))
    if os.path.exists(recipe_ws):
        shutil.rmtree(recipe_ws, ignore_errors=True)